### ISSUE TITLE
[IOS] App crashes on login

### ISSUE THREAD

**Issue by Trteich** [darwin-morocho/flutter-facebook-auth#114]
Hi, guys.
On executing `await FacebookAuth.instance.login()` app crashes with exception:

Terminating app due to uncaught exception 'InvalidOperationException', reason: 'As of v9.0, you must initialize the SDK prior to calling any methods or setting any properties. You can do this by calling `FBSDKApplicationDelegate`'s `application:didFinishLaunchingWithOptions:` method. Learn more: https://developers.facebook.com/docs/ios/getting-started'
terminating with uncaught exception of type NSException

**Expected behaviour:** screen with facebook login woul be launched

I have directly followed installation instruction from [here](https://facebook.meedu.app)

IOS 14.6
Library v3.5.0

**Flutter doctor**
```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 2.2.2 at C:\Program Files\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Tretich\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\Tretich\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124

• No issues found!
```

**pubspec.yaml**
```
version: 2.1.0+103

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_crashlytics: ^2.0.6
  url_launcher: ^6.0.3
  dio: ^4.0.0
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  package_info: ^2.0.2
  device_info: ^2.0.2
  camera: ^0.5.7+4
  path_provider: ^2.0.2
  carousel_slider: ^1.4.1
  image_picker: ^0.8.1+2
  video_player: ^2.1.6
  web_socket_channel: ^2.1.0
  vector_math: ^2.1.0
  latlong: ^0.6.1
  native_device_orientation: ^1.0.0
  animator: ^1.0.0+5
  location: ^4.3.0
  background_locator: 
    path: ./hijacking/background_locator-1.6.2+1/
  flutter_compass: ^0.6.1
  mapbox_gl:
    path: ./hijacking/mapbox_gl-0.7.0-hijacking/
  intl: ^0.17.0
  video_compress: ^3.0.0
  geocoder: ^0.2.1
  scrollable_positioned_list: ^0.1.10
  move_to_background: ^1.0.2
  sqflite: ^2.0.0+3
  gallery_saver:
    path: ./hijacking/gallery_saver_2.1.0_temp/  #temporrary solution until android compilation bug not solved
  uuid: ^3.0.4
  animated_widgets: ^1.1.0
  onesignal_flutter: ^3.0.0
  http: ^0.13.3
  async: ^2.6.1
  photo_view: ^0.11.1
  mailto: ^2.0.0
  app_settings: ^4.1.1
  permission_handler: ^8.1.2
  screen: ^0.0.5
  flutter_svg: ^0.22.0
  flutter_facebook_auth: ^3.5.0
  location_permissions: ^4.0.0
  media_picker:
    path: ./hijacking/flutter_media_picker/
  flutter_absolute_path: ^1.0.6
  mime: 1.0.0
  twitter_login: ^4.0.1
  dart_twitter_api: ^0.5.3
  firebase_core: ^1.3.0
  internet_connection_checker: ^0.0.1+1
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  assets:
    - assets/images/
    - assets/videos/
    - icons/

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
        - asset: fonts/FiraSans-Book.otf
          weight: 300
        - asset: fonts/FiraSans-Medium.ttf
          weight: 500
    - family: SFPro
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

```

**info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>H&amp;H</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>*myappid*</string>
				<string>hh</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FacebookAppID</key>
	<string>*myappId*</string>
	<key>FacebookDisplayName</key>
	<string>Highways &amp; Hailstones</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
                <string>fbauth2</string>
		<string>twitter</string>
		<string>twitterauth</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>MinimumOSVersion</key>
	<string>10.0</string>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSAppleMusicUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSCalendarsUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSCameraUsageDescription</key>
	<string>H&amp;H needs access to your camera to take photos &amp; videos of your chase</string>
	<key>NSContactsUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>The app needs access to your location to record route of your chases.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>H&amp;H needs access to your microphone to take videos with sound of your chase</string>
	<key>NSMotionUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>We need permission to share photos/videos from your library and save photos/videos to your camera roll</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>You should never see this, please contact us</string>
	<key>UIAppFonts</key>
	<array>
		<string>Poppins-Regular.ttf</string>
		<string>Poppins-Bold.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
</dict>
</plist>
```

**AppDelegate.swift**
```
import UIKit
import Flutter
import Firebase
import background_locator

func registerPlugins(registry: FlutterPluginRegistry) -> () {
    GeneratedPluginRegistrant.register(with: registry)
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    BackgroundLocatorPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
