### ISSUE TITLE
flutter_facebook_auth doesn't work with image_picker

### ISSUE THREAD

**Issue by afdesk** [darwin-morocho/flutter-facebook-auth#124]
**Describe the bug**
`image_picker 0.8.2` doesn't work with added ` flutter_facebook_auth 3.5.0`.
if I try to use `image_picker` features I'll receive next error in the logs:
```
E/flutter (10775): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter (10775): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (10775): <asynchronous suspension>
E/flutter (10775): #1      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188:20)
E/flutter (10775): <asynchronous suspension>
```
but the same code works fine without ` flutter_facebook_auth`.

**Environment**
`flutter doctor -v`: No issues found!
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  provider: ^5.0.0
  cached_network_image: ^3.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  uuid: 3.0.4
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  firebase_storage: ^8.1.3
  json_serializable: ^4.1.3
  google_sign_in: ^5.0.5
  flutter_facebook_auth: ^3.5.0
  flutter_signin_button: ^2.0.0
  image_picker: ^0.8.2
```

**To Reproduce**
```dart
    final XFile? imageFile = await picker.pickImage(
      source: imageSource,
    );
```
