### ISSUE TITLE
Not working in first connection

### ISSUE THREAD

**Issue by mlorthios** [darwin-morocho/flutter-facebook-auth#127]
**Describe the bug**
Hi, I have a small problem when first logging in on iOS, I have for the moment configured on Android, when I confirm my account, the connection is lost and nothing is returned. However the application is well added to my Facebook account and when I try again to reconnect it works. The bug only occurs if the application is not added to Facebook the first time.

**Environment**
Add your `flutter doctor -v`
Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 11.1 20C69 darwin-x64, locale fr-FR)
    • Flutter version 2.3.0-24.1.pre at /Users/mathis/fvm/versions/beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (4 weeks ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mathis/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone de Mathis (mobile) • 00008030-0019245A2620802E • ios            • iOS 14.5
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

Add your `pubspec.yaml`
```
name: appname
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^2.0.2+4
  platform_maps_flutter: ^1.0.2
  graphql: ^5.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  intl_phone_number_input: ^0.7.0+2
  sign_in_with_apple: ^3.0.0
  http: ^0.13.3
  json_serializable: ^4.1.4
  json_annotation: ^4.1.0
  build_runner: ^2.0.6
  top_snackbar_flutter: ^1.0.0
  flutter_facebook_auth: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
```

Add your `Info.plist`
```
<key>CFBundleURLSchemes</key>
	<array>
		<string>fbmy app id</string>
	</array>
	</dict>
	</array>
	<key>FacebookAppID</key>
	<string>my app id</string>
	<key>FacebookClientToken</key>
	<string>my client token</string>
	<key>FacebookDisplayName</key>
	<string>my app name</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fbapi20130214</string>
		<string>fbapi20130410</string>
		<string>fbapi20130702</string>
		<string>fbapi20131010</string>
		<string>fbapi20131219</string>
		<string>fbapi20140410</string>
		<string>fbapi20140116</string>
		<string>fbapi20150313</string>
		<string>fbapi20150629</string>
		<string>fbapi20160328</string>
		<string>fbauth</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
```

**To Reproduce**
Set up Facebook Auth and make a first connection 

**Screenshots**
<img width="368" alt="Screenshot at Jul 25 20-43-14" src="https://user-images.githubusercontent.com/31793724/126909902-934eddd8-f9d6-48a1-95a7-9782ac475b81.png">
