### ISSUE TITLE
FBSDKCoreKit (~> 12.0.2)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by YDA93** [darwin-morocho/flutter-facebook-auth#176]
**Describe the bug**
pod install Error.

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-KW)
    • Flutter version 2.5.3 at /Users/yousefalmutairi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yousefalmutairi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • SM G965F (mobile) • 2449cd411a1c7ece          • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)   • 00008030-000134911482802E • ios            • iOS 15.1 19B74
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

**Pubspec**
```
name: fesale
description: Buy and Sell Everything.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.17+19
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.4
  connectivity_plus: ^2.0.2
  convex_bottom_bar: ^3.0.0
  country_code_picker: ^2.0.2
  crypto: ^3.0.1
  file_picker: ^4.1.6
  firebase_analytics: ^8.3.4
  firebase_app_check: ^0.0.2+3
  firebase_auth: ^3.1.4
  firebase_auth_oauth: ^1.1.0
  firebase_core: ^1.8.0
  firebase_crashlytics: ^2.2.4
  firebase_database: ^8.0.1
  firebase_messaging: ^10.0.9
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.3
  flutter_html: ^2.1.5
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_ringtone_player: ^3.1.0
  flutter_secure_storage: ^4.2.1
  flutter_slidable: ^0.6.0
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ">= 4.7.0"
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.0

  http: ^0.13.4
  image_picker: ^0.8.4+3
  intl: ^0.17.0

  intl_phone_number_input: ^0.7.0+2
  introduction_screen: ^2.1.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  percent_indicator: ^3.4.0
  permission_handler: ^8.2.5
  photo_view: ^0.13.0
  pin_code_fields: ^7.3.0

  provider: ^6.0.1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.2.0
  soundpool: ^2.2.0
  timeago: ^3.1.0
  twitter_login: ^4.0.1
  url_launcher: ^6.0.12
  validators: ^3.0.0
  webview_flutter: ^2.1.2

dev_dependencies:
  analyzer: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  logger: ^1.1.0

dependency_overrides:
  font_awesome_flutter:
    path: assets/font_awesome_flutter-master

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/introduction/
    - assets/sounds/
```

**AppDelegate.swift**

```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    let providerFactory = AppCheckDebugProviderFactory()
    AppCheck.setAppCheckProviderFactory(providerFactory)

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**/app/res/values/strings.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="app_name">FeSale</string>
  <string name="facebook_app_id">610824806751141</string>
  <string name="fb_login_protocol_scheme">fb610824806751141</string>

  <string name="new_message_from">%1$s sent you message</string>

  <string name="new_follower">New follower</string>
  <string name="user_followed_you">%1$s have followed you</string>

  <string name="new_rating">New rating</string>
  <string name="left_positive_rating">%1$s left positive rating</string>
  <string name="left_negative_rating">%1$s left negative rating</string>
  <string name="completed_ad_rating_title">How was your experience with %1$s</string>
  <string name="completed_ad_rating_body">Tell us what you think</string>

  <string name="offer_accepted_action">%1$s have accepted your offer</string>
  <string name="apply_for_job_accepted_action">%1$s have accepted your job application</string>
  <string name="request_item_accepted_action">%1$s have accepted your item request</string>
  <string name="request_dm_accepted_action">%1$s have accepted your DM request</string>

  <string name="offer_rejected_action">%1$s have rejected your offer</string>
  <string name="apply_for_job_rejected_action">%1$s have rejected your job application</string>
  <string name="request_item_rejected_action">%1$s have rejected your item request</string>
  <string name="request_dm_rejected_action">%1$s have rejected your DM request</string>

  <string name="question_replies">%1$s left a comment</string>
  <string name="offer_replies">%1$s have offered: %2$s</string>
  <string name="apply_for_job_replies">%1$s applied to job</string>
  <string name="request_item_replies">%1$s requested this item</string>
  <string name="request_dm_replies">%1$s requested to DM</string>
</resources>
```
**To Reproduce**
ios min version '11.4'

**Expected behavior**
```
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: L5GMX9Y2JD
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Firebase
      - FirebaseFirestore
      - Flutter
      - cloud_firestore
      - connectivity_plus
      - file_picker
      - firebase_analytics
      - firebase_app_check
      - firebase_auth
      - firebase_auth_oauth
      - firebase_core
      - firebase_crashlytics
      - firebase_database
      - firebase_messaging
      - flutter_facebook_auth
      - flutter_local_notifications
      - flutter_ringtone_player
      - flutter_secure_storage
      - google_sign_in
      - image_picker
      - libphonenumber
      - libphonenumber_plugin
      - package_info_plus
      - path_provider
      - permission_handler
      - share_plus
      - shared_preferences
      - sign_in_with_apple
      - soundpool
      - sqflite
      - twitter_login
      - url_launcher
      - video_player
      - wakelock
      - webview_flutter_wkwebview
    Fetching external sources
    -> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.5.0`
      > Copying FirebaseFirestore from `/Users/yousefalmutairi/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/4a6ae73fd5031fbeea3f67ef6666bf17` to `Pods/FirebaseFirestore`
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    cloud_firestore: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
    -> Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    firebase_analytics: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_app_check` from `.symlinks/plugins/firebase_app_check/ios`
    firebase_app_check: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    firebase_auth: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_auth_oauth` from `.symlinks/plugins/firebase_auth_oauth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
    firebase_crashlytics: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
    firebase_database: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    firebase_messaging: Using user specified Firebase SDK version '8.5.0'
    -> Fetching podspec for `flutter_facebook_auth` from `.symlinks/plugins/flutter_facebook_auth/ios`
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_ringtone_player` from `.symlinks/plugins/flutter_ringtone_player/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `libphonenumber` from `.symlinks/plugins/libphonenumber/ios`
    -> Fetching podspec for `libphonenumber_plugin` from `.symlinks/plugins/libphonenumber_plugin/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `share_plus` from `.symlinks/plugins/share_plus/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sign_in_with_apple` from `.symlinks/plugins/sign_in_with_apple/ios`
    -> Fetching podspec for `soundpool` from `.symlinks/plugins/soundpool/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `twitter_login` from `.symlinks/plugins/twitter_login/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter_wkwebview` from `.symlinks/plugins/webview_flutter_wkwebview/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.7.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_6_1.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.2/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_6_d_6.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/6/d/6/libPhoneNumber-iOS/0.9.15/libPhoneNumber-iOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/6.0.2/GoogleSignIn.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.5.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_9_b_5.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/11.2.1/FBSDKCoreKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_3_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/11.2.1/FBSDKLoginKit.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In snapshot (Podfile.lock):
        FBSDKCoreKit (= 11.2.1, ~> 11.2.0, ~> 11.2.1)
      In Podfile:
        flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
          FBSDKCoreKit (~> 12.0.2)
    Specs satisfying the `FBSDKCoreKit (= 11.2.1, ~> 11.2.0, ~> 11.2.1), FBSDKCoreKit (~> 12.0.2)` dependency were found, but they required a higher minimum deployment target.
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/bin/pod:23:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.2/libexec/bin/pod:23:in `<main>'
Exception: Error running pod install
Exited (sigterm)

```

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
