### ISSUE TITLE
facebook login not working after upgrading flutter

### ISSUE THREAD

**Issue by imSaharukh** [darwin-morocho/flutter-facebook-auth#193]
**Describe the bug**
after upgrading the flutter version the facebook auth is not working
![image](https://user-images.githubusercontent.com/25554766/144594348-dbced616-d5b3-4de4-b3e2-41d090c9e2c9.png)

**Environment**

flutter doctor -v
``` 
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en-BD)
    • Flutter version 2.8.0-3.2.pre at /Volumes/SSD2/FlutterSrc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2901cd7208 (2 weeks ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/imsaharukh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 2 categories.
```

<details>

  <summary>pubspec.yaml</summary>

  ```
name: chatout_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+20

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  get: 4.1.4
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0
  flutter_feather_icons: ^2.0.0+1
  flutter_facebook_auth: ^3.5.6+3
  dio: ^4.0.0
  expandable: ^5.0.1
  # material_floating_search_bar: ^0.3.4
  bottom_sheet: ^1.0.1
  hive: ^2.0.4
  flutter_spinkit: ^5.0.0
  hive_flutter: ^1.0.0
  multi_select_flutter: ^4.0.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  intl: ^0.17.0
  image_picker: ^0.7.5+2
  http_parser: ^4.0.0
  cached_network_image: ^3.0.0
  full_screen_image_null_safe: ^2.0.0
  pinch_zoom: ^0.1.0-nullsafety.0
  persistent_bottom_nav_bar: ^4.0.2
  firebase_core: ^1.2.1
  fcm_config: ^3.0.9
  device_info: ^2.0.2
  google_nav_bar: ^5.0.5
  url_launcher: ^6.0.12
  flutter_launcher_icons: ^0.9.0
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.2
  ansicolor: ^2.0.1
  dio_http_cache: ^0.3.0
  shimmer: ^2.0.0
  new_version: ^0.2.3
  fast_immutable_collections: ^7.0.3
  flutter_reorderable_list: ^1.1.0
  flex_color_picker: ^2.1.2
  flutter_inappwebview: ^5.3.2
  flutter_typeahead: ^3.2.1
  
  

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.1.1

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/chatout-appicon.png"
  remove_alpha_ios: true




  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#   To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/placeholders/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: Circular-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf
    - family: Circular-Medium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
    - family: Circular-Bold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

<details>

  <summary>info.plist</summary>

  ```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>chatout</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>chatout_flutter</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb139855594719xxxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>139855594719xxxx</string>
	<key>FacebookDisplayName</key>
	<string>chatout</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Used to capture audio for image picker plugin</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>


```

</details>

</details>

<details>

  <summary>AppDelegate.swift</summary>

  ```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>chatout</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>chatout_flutter</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb139855594719xxxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>139855594719xxxx</string>
	<key>FacebookDisplayName</key>
	<string>chatout</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Used to capture audio for image picker plugin</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>


```

</details>

</details>

<details>

  <summary>MainActivity</summary>

  ```
package co.chatout.chatout_flutter

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}



```

</details>

</details>

<details>

  <summary>AndroidManifest.xml</summary>

  ```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.chatout_flutter">
    <uses-permission android:name="android.permission.INTERNET"/>
    <!-- Provide required visibility configuration for API level 30 and above -->
        <queries>
    <!-- If your app opens https URLs -->
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="https" />
    </intent>
    <!-- If your app makes calls -->
    <intent>
        <action android:name="android.intent.action.DIAL" />
        <data android:scheme="tel" />
    </intent>
    <!-- If your app emails -->
    <intent>
        <action android:name="android.intent.action.SEND" />
        <data android:mimeType="*/*" />
    </intent>
    </queries>

    <application
        android:label="chatout_flutter"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />



    </application>

            <queries>
            <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
        </queries>
</manifest>


```

</details>

</details>

<details>

  <summary>/app/res/values/strings.xml</summary>

  ```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">chatout</string>
    <string name="facebook_app_id">139855594719xxxx</string>
    <string name="fb_login_protocol_scheme">fb139855594719xxxx</string>
</resources>


```

</details>

**To Reproduce**
```dart
  Future<void> loginToFacebook() async {
    showLoader();
    FacebookAuth facebook = FacebookAuth.instance;

    await facebook.logOut();

    final LoginResult result = await facebook.login(
      permissions: [
        "public_profile",
        "email",
        "pages_show_list",
        "pages_messaging",
        "pages_manage_metadata",
        "instagram_basic",
        "instagram_manage_messages",
        "pages_read_engagement",
        "pages_manage_metadata",
      ],
    );
    if (result.status == LoginStatus.success) {
      // you are logged
      final AccessToken accessToken = result.accessToken;

      var longLivedAccessToken =
          await getLongUserAccessToken(accessToken.token);

      print("long access token $longLivedAccessToken");
      List<PageData> pages =
          await getPagesToSub(longLivedAccessToken).catchError((error) {
        errorMessage();
      });

      pages.forEach((element) {
        //printInfo(info: "pages:  ${element.name}");
      });
      Get.back();

      print(accessToken.userId);

      List<PageData> pageResult =
          await showPageSelect(pages, Get.context).catchError((error) {
        errorMessage();
      });

      await connectFbWithServer(pageResult);
    } else {
      Get.back();
      Get.defaultDialog(
        title: "Error",
        content: Text(result.status.toString()),
      );
    }
  }
```

**Expected behavior**
Everything was working as expected, then after upgrading my flutter version this issue occurs 

**Screenshots**
![image](https://user-images.githubusercontent.com/25554766/144592908-66b20a43-6f96-4c7f-9af6-3f63f92806ea.png)
![image](https://user-images.githubusercontent.com/25554766/144592972-d24c94b2-86af-4370-8513-364d136dfca3.png)
