### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by Nandan-Wewhare** [darwin-morocho/flutter-facebook-auth#218]
**Describe the bug**
Every time `final LoginResult loginResult = await FacebookAuth.instance.login();` is called.
Setup only for Android is completed according to the steps on:
https://facebook.meedu.app/docs/4.x.x/android

**Environment**
`flutter doctor -v`
```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.527], locale en-IN)
    • Flutter version 2.10.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\nanda\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\nanda\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Redmi Note 7 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

`pubspec.yaml`
```
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  elegant_notification:
    git:
      url: https://github.com/lalitjarwal/Elegant-Notification.git
      ref: main
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.1.1
  flutter_html: ^2.2.1
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.1
  geolocator: ^8.0.1
  get: ^4.6.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  lottie: ^1.2.1
  onesignal_flutter: ^3.2.7
  pinput: ^1.2.2
  shared_preferences: ^2.0.11
  tcard: ^1.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
```
 `MainActivity`
_MainActivity.kt_
```
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

 `AndroidManifest.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.penpal">
    <queries>
      <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
    </queries>
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
   <application
        android:label="PenPal"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
   	        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

`/app/res/values/strings.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">471914431262398</string>
  <string name="facebook_client_token">d988cc406e90720eb2612e0d426f3ecc</string>
</resources>
```
