### ISSUE TITLE
CONNECTION_FAILURE: CONNECTION_FAILURE Login Failed

### ISSUE THREAD

**Issue by afzl-wtu** [darwin-morocho/flutter-facebook-auth#227]
**Describe the bug**
I have imported latest package (flutter_facebook_auth: ^4.1.2) and followed all the documentaion on the website https://facebook.meedu.app/ for android. Now when I click on "sign in with facebook" Button . It takes me to facebook app where I allow the authorization. After this it closes and I am shifted back to app But I am not signed in the app.
I got the following output from the debug Console:
PP: result.status: Login Failed
PP: result.message: CONNECTION_FAILURE: CONNECTION_FAILURE

I confirm internet is working fine and even I used vpn to check if it is problem of my local internet. I even cleared my cache by flutter clean command. I have also added required fields on facebook including SHA-1 in form of Base64 and turned on facebook authentication.

**To Reproduce**
Flutter Code:
```
 Future<String?>? _signInWithFacebook() async {
    final LoginResult result = await FacebookAuth.instance
        .login();
    if (result.status == LoginStatus.success) {
      print(' Logged In');
    } else {
      print('PP: result.status ${result.status}');
      print('PP: result message: ${result.message}');
    }
```

**Environment**
Add your `flutter doctor -v`

```C:\Users\afzlw\Documents\@Projects\flutter\dot_now>flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-GB)
    • Flutter version 2.10.4 at C:\Users\Public\@Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\afzlw\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.        
      27) (emulator)
    • Windows (desktop)                  • windows            • windows-x64    • Microsoft Windows    
      [Version 10.0.22000.556]
    • Edge (web)                         • edge               • web-javascript • Microsoft Edge       
      100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

Add your `pubspec.yaml`
```
name: dot_now
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  easy_mask: ^2.0.1
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  flutter_countdown_timer: ^4.1.0
  firebase_database: ^9.0.9
  flutter_facebook_auth: ^4.1.2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  introduction_screen: ^3.0.2
  pinput: ^2.2.7
  sembast: ^3.2.0
  sentry: ^6.4.0
  vxstate: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/landing_page/

```
Add your `Info.plist`

Not relevent as I am testing for android only.

Add your `AppDelegate.swift`

Not relevent as I am testing for android only.

Add your `MainActivity`
```
package pk.dotnow.dot_now

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```
Add your `AndroidManifest.xml`
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="pk.dotnow.dot_now">
    <queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
    </queries>

   <application
        android:label="dot_now"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>

```

Add your `/app/res/values/strings.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="facebook_app_id">516060370HIDDEN</string>
    <string name="facebook_client_token">c95ccef4b55f41dcd80289c849HIDDEN</string>
</resources>
```
