### ISSUE TITLE
Facebook auth issue

### ISSUE THREAD

**Issue by Nurdiyor** [darwin-morocho/flutter-facebook-auth#268]
### What version are you using?

 flutter_facebook_auth:4.4.0

### What OS and version are you using to local deploy your application?

widows 10

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  #  http: ^0.13.3
  dio: ^4.0.4
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.7
  image_picker: ^0.8.4+6
  flutter_svg: ^1.0.3
  firebase_messaging: ^11.2.6
  google_sign_in: ^5.2.4
  share: ^2.0.4
  intl: ^0.17.0
  file_picker: ^4.6.1
  flutter_facebook_auth: ^4.4.0
  sign_in_with_apple: ^3.3.0
  flutter_stripe: ^3.1.0
  flutter_spinkit: ^5.1.0
  package_info_plus: ^1.3.0
  firebase_core: ^1.12.0
  mask_text_input_formatter: ^2.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

### Describe the Bug

 You're calling logging in Facebook with an activity supports androidx activity result APIs. Please follow our document to upgrade to new APIs to avoid overriding onActivityResult().

### Expected Behavior

The app cannot open facebook app login when it installed.But When i remove facebook app it works with browser

### To Reproduce

  LoginResult loginResult = await FacebookAuth.instance.login();
        if (loginResult.status == LoginStatus.success) {
          // FacebookAuthProvider.credential(loginResult.accessToken!.token);
          onSignIn(loginResult);
        }

### flutter doctor -v

```shell
PS C:\flutter\project> flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale ru-RU)
    • Flutter version 3.0.5 at C:\microstar\flutter\sdk\flutter_windows_3.0.5\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (12 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • 2201117TG (mobile) • 70267434 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 103.0.1264.71

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
