### ISSUE TITLE
User has cancelled login with facebook

### ISSUE THREAD

**Issue by DenisKen** [darwin-morocho/flutter-facebook-auth#272]
### What version are you using?

4.4.1

### What OS and version are you using to local deploy your application?

Android 11

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: finsi
description: <CHANGE DESCRIPTION HERE>

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1-dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.13
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.0
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_facebook_auth: ^4.4.1
  google_sign_in: ^5.0.4
  path_provider: ^2.0.3
  sign_in_with_apple: ^4.0.0
  share_plus: ^4.0.6

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app/app_icon.png"
  adaptive_icon_background: "assets/images/app/background.png"
  adaptive_icon_foreground: "assets/images/app/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data.json
    - assets/images/logos/
    - assets/images/icons/
    - assets/finsi_user_data.json

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

When I hit button to login on facebook, the facebook screen **opens and closes immediatly**! 

The result of `LoginResult` `status` is `LoginStatus.cancelled` and  `message` is `User has cancelled login with facebook`

This is my code:
```
void _loginFacebook(context) async {
    print("Login: Facebook >>>>>>>>>");

    await FacebookAuth.instance.logOut();
    final faceResult = await FacebookAuth.instance.login();
    
    if (faceResult.status == LoginStatus.success) {
      print("Login: Result Facebook Success");
      //Provider.of<AuthNotifier>(context, listen: false)
        //  .setStatus(AuthStatus.authenticating);

      _requestLogin(context, "facebook", faceResult.accessToken.token);
    }
    print(faceResult.status);
    print(faceResult.message);
  }```

### Expected Behavior

The expected behavior is show up the facebook login screen

### To Reproduce

Following code

### Relevant log output

_No response_

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [versÆo 10.0.22000.856], locale pt-BR)
    • Flutter version 3.0.1 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Denis\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.16299.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include     
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.67.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (5 available)
    • ASUS I005DA (mobile)    • M1AIKN054214ZHF • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554   • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows         • windows-x64    • Microsoft Windows [versÆo 10.0.22000.856]
    • Chrome (web)            • chrome          • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)              • edge            • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
```
