### ISSUE TITLE
Inconsistent expire date between android and ios

### ISSUE THREAD

**Issue by Daimioo** [darwin-morocho/flutter-facebook-auth#281]
### What version are you using?

4.3.4+2

### What OS and version are you using to local deploy your application?

macOs 12.2

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
environment:
  flutter: 3.0.3
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  camera: ^0.9.8+1
  cloud_firestore: ^3.1.18
  cloud_functions: ^3.2.17
  equatable: ^2.0.3
  sentry_flutter: ^6.6.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_dynamic_links: ^3.0.2
  firebase_messaging: ^11.4.2
  firebase_storage: ^10.2.18
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  flutter_speed_dial: ^6.0.0
  geoflutterfire: ^3.0.3
  google_maps_flutter: ^2.1.8
  html: ^0.15.0
  http: ^0.13.4
  image_cropper: ^1.5.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  location: ^4.4.0
  rxdart: ^0.27.4
  share_plus: ^4.0.10
  timeago: ^3.2.2
  transparent_image: ^2.0.0
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  video_player: ^2.4.5
  another_flushbar: ^1.10.29
  audioplayers: ^0.20.1
  in_app_purchase: ^3.0.6
  permission_handler: ^10.0.0
  badges: ^2.0.3
  flutter_app_badger: ^1.4.0
  flutter_facebook_auth: ^4.3.4+2
  mask: ^1.0.3
  lottie: ^1.3.0
  readmore: ^2.2.0
```

### Describe the Bug

When calling the login method and getting the access token from the response I am receiving different outputs for the expirationDate, on a ios simulator (ios 15.5 iPhone 13 mini) I receive the value ```4000-12-31 20:00:00.000``` and on the android emulator (Pixel 2 API 33) I receive ```275760-09-12 20:00:00.000```.

### Expected Behavior

Same expiration dates for ios and android.

### To Reproduce

call the login method from the FacebookAuth package
print the access token on an android device
print the access token on an ios device

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5 21G72 darwin-arm, locale en-BR)
    • Flutter version 3.0.3 at /Users/rafaelpontesbrasil/fvm/versions/3.0.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rafaelpontesbrasil/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
