### ISSUE TITLE
plugin appearing in my app when ive never used it

### ISSUE THREAD

**Issue by Technorocker** [darwin-morocho/flutter-facebook-auth#282]
### What version are you using?

im not but flutter_facebook_auth_web 3.2.0

### What OS and version are you using to local deploy your application?

windows 10

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_splash_screen: ^1.2.0
  animated_theme_switcher: "^2.0.5"
  animations: ^2.0.2
  audioplayers: ^1.0.1
  audio_waveforms: ^0.1.4
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.0
  #cached_video_player: ^2.0.3
  camera:
    git:
      url: https://github.com/flutter/plugins
      path: packages/camera/camera
      ref: 9e46048ad2e1f085c1e8f6c77391fa52025e681f
  #camerawesome: ^0.3.0+1
  cloud_firestore: ^3.1.18
  connectivity_plus: ^2.2.1
  #contacts_service: ^0.6.3
  convex_bottom_bar: ^3.0.0
  device_info_plus: ^4.1.2
  elliptic_text: ^1.0.1+9
  email_validator: ^2.0.1
  file_picker: ^5.0.1
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.4.2
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_storage: ^10.3.5
  flutter_cache_manager: ^3.3.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_local_notifications: ^9.9.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9+1
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.0.3
  flutter_zoom_drawer: ^3.0.2
  font_awesome_flutter: ^10.1.0
  flutterfire_ui: ^0.4.2+3
  get: ^4.6.5
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  image: ^3.1.3
  #image_gallery_saver: ^1.7.1
  #image_picker: ^0.8.4+9
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  #local_auth: ^2.0.0
  #logger: ^1.1.0
  meta: ^1.7.0
  #mobile_number: ^1.0.4
  overlay_support: ^2.0.1
  page_transition: ^2.0.9
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shimmer_animation: ^2.1.0+1
  #sms_autofill: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  video_compress: ^3.1.1
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/md_files/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Elianto
      fonts:
        - asset: assets/fonts/Elianto-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Cooper
      fonts:
        - asset: assets/fonts/Cooper-Black-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/ic_launcher.png"
  image_path_android: "assets/images/launcher/ic_launcher.png"
  remove_alpha_ios: true
```

### Describe the Bug

this plugin is showing up giving me errors when ive never installed or ever used this plugin, why is it showing up at all?

### Expected Behavior

shouldnt even exist in my app

### To Reproduce

no idea

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-CA)
    • Flutter version 3.3.0 on channel stable at D:\Andre\Projects\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (9 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at D:\Andre\Programs\SDKs\Android-SDK
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: D:\Andre\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at D:\Andre\Programs\Visual Studio\Main Files
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Andre\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (5 available)
    • SM G975W (mobile)            • R58N326N0MD   • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]        
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.53
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available
```
