### ISSUE TITLE
Unable to Login in Android

### ISSUE THREAD

**Issue by 2shrestha22** [darwin-morocho/flutter-facebook-auth#284]
### What version are you using?

4.4.1

### What OS and version are you using to local deploy your application?

Tested on Android 12, 11

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: flutter_app
description: Flutter App
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.2.3+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #router
  auto_route: ^5.0.0

  #dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  #state management
  flutter_bloc: ^8.1.1


  #data models
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

  #functional programmings
  dartz: ^0.10.1

  #network requests
  dio: ^4.0.6
  gql_dio_link: ^0.2.2
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: 4.1.1
  flutter_native_splash: ^2.2.7
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.2
  dots_indicator: ^2.1.0
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  google_sign_in: ^5.4.0
  flutter_facebook_auth: 4.3.4
  sign_in_with_apple: ^4.1.0
  logger: ^1.1.0
  formz: ^0.4.1
  async: ^2.8.2
  country_picker: ^2.0.15
  flutter_udid: ^2.0.0
  ferry: ^0.11.0+1
  ferry_hive_store: ^0.4.5
  local_auth: ^2.1.1
  firebase_crashlytics: ^2.8.5
  image_picker: ^0.8.5+3
  simple_s3: 0.3.2
  flutter_html: ^3.0.0-alpha.5
  in_app_purchase: ^3.0.6
  flutter_local_notifications: ^9.7.0
  flutter_multi_formatter: ^2.5.8
  flutter_stripe: ^4.0.0
  infinite_scroll_pagination: ^3.2.0
  permission_handler: ^10.0.0
  file_picker: ^5.0.1
  package_info_plus: ^1.4.3
  dropdown_button2: ^1.7.1
  flutter_typeahead: ^4.0.0
  google_place: ^0.4.7
  hydrated_bloc: ^9.0.0-dev.3
  path_provider: ^2.0.11
  bloc_concurrency: ^0.2.0
  amazon_s3_cognito:
    git:
      url: https://github.com/2shrestha22/amazon_s3_cognito.git
      ref: flutter3_compatible
  url_launcher: ^6.1.5
  pdfx: ^2.2.0
  internet_file: ^1.2.0
  gql_error_link: ^0.2.3
  gql_transform_link: ^0.2.3-alpha+1660256327655
  rxdart: ^0.27.5
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.1.11
  json_serializable: ^6.3.0
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.3
  auto_route_generator: ^5.0.0

  mocktail: ^0.3.0
  bloc_test: ^9.1.0

  flutter_launcher_icons: ^0.10.0

  flutter_gen_runner: ^4.3.0  
  import_sorter: ^4.6.0
  ferry_generator:
    git:
      url: https://github.com/2shrestha22/ferry.git
      ref: disable-lint
      path: packages/ferry_generator

# dependency_overrides:
#   # https://github.com/flutter/flutter/issues/107454#issuecomment-1182975416
#   in_app_purchase_android: 0.2.2+8

flutter:
  uses-material-design: true
  # internationalization
  generate: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf


flutter_native_splash:
  background_image: assets/images/splash.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"

import_sorter:
  comments: false
  ignored_files:
    - \/gen\/*
    - .g.dart
    - .freezed.dart
    - .gr.dart
    - .gen.dart
```

### Describe the Bug

After selecting facebook account to login, the login overlay pops and screen (app screen) gets stuck until I press back manually. Hence login result gives cancelled error.
After canceling login process overlay pops and then UI gets stucked.

### Expected Behavior

Should not stuck after chrome view is closed.

### To Reproduce

Login with cancel the login by pressing x button on top left or finish the login process. App UI will stuck after overlay pops.

### Relevant log output

```shell
W/class com.facebook.login.LoginManager( 5042): You're calling logging in Facebook with an activity supports androidx activity result APIs. Please follow our document to upgrade to new APIs to avoid overriding onActivityResult().
Reloaded 0 libraries in 229ms.
W/ActivityResultRegistry( 5042): Dropping pending result for request FragmentManager:StartActivityForResult: ActivityResult{resultCode=RESULT_OK, data=Intent { act=CustomTabActivity.action_customTabRedirect flg=0x24000000 cmp=com.sentiment.app.dev/com.facebook.CustomTabMainActivity (has extras) }}
```

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.0.5, on Arch Linux 5.19.7-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/sangam/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/sangam/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /home/sangam/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.1
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64   • Arch Linux 5.19.7-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
