### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by shahid31346** [darwin-morocho/flutter-facebook-auth#290]
### What version are you using?

^5.0.0-dev.4

### What OS and version are you using to local deploy your application?

windows 10

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: foodybite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.13
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_staggered_grid_view: ^0.6.1
  photo_view: ^0.13.0
  easy_localization: ^3.0.0
  shimmer: ^2.0.0
  package_info_plus: ^1.3.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.18
  video_player: ^2.4.7
  modal_bottom_sheet: ^2.0.0
  #flutter_qr_bar_scanner: ^2.0.0
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  chewie: ^1.2.2
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.1
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.6
  linkedin_login: ^2.2.1
  flutter_facebook_auth: ^5.0.0-dev.4
  permission_handler: ^10.0.2
 

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/languages/
  
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
```

### Describe the Bug

i configure every as per your documentation but still no implementation found

### Expected Behavior

facebook successfull login and info

i did everything 
flutter clean 
keyhash new config 
strings.xml

### To Reproduce

  loginFb() async {
 
    //final LoginResult result = await FacebookAuth.instance.login();

    final result =
        await FacebookAuth.i.login(permissions: ['public_profile']);
    if (result.status == LoginStatus.success) {
      final userData = await FacebookAuth.i.getUserData();
      print(userData);
    }

    final _userData = await FacebookAuth.instance.getUserData();
    print(_userData);
  }

### Relevant log output

```shell
E/flutter (30021): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)
E/flutter (30021): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (30021): <asynchronous suspension>
E/flutter (30021): #1      FacebookAuthPlatformImplementation.login (package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:34:22)     
E/flutter (30021): <asynchronous suspension>
E/flutter (30021): #2      _LoginPageState.loginFb (package:foodybite/pages/login/login_page.dart:185:9)
E/flutter (30021): <asynchronous suspension>
```

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.1826], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)
[√] Connected device (5 available)
[√] HTTP Host Availability
```
