### ISSUE TITLE
Latest plugin still required FacebookSdk.sdkInitialize

### ISSUE THREAD

**Issue by tovidd** [darwin-morocho/flutter-facebook-auth#293]
### What version are you using?

flutter_facebook_auth: ^4.4.1+1

### What OS and version are you using to local deploy your application?

MacOS Monterey 12.6

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: flutter_apps
description: A new Flutter application.
publish_to: none
version: 1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  add_2_calendar: ^2.1.3
  adjust_sdk: ^4.32.0
  app_review: ^2.1.2+1
  auto_size_text: ^3.0.0
  call_log: ^4.0.0
  carousel_slider: ^4.1.1
  country_pickers: ^2.0.0
  device_calendar: ^4.2.0 
  device_info: ^2.0.3 
  dio: ^4.0.6
  equatable: ^2.0.5
  expandable: ^5.0.1
  expandable_bottom_sheet: ^1.1.1+1
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_messaging: ^13.1.0
  firebase_performance: ^0.8.3+3
  flare_flutter: ^3.0.0 #?
  flutter_bloc: ^8.1.1
  flutter_card_swipper: ^0.4.0 
  flutter_exif_rotation: ^0.5.1
  flutter_facebook_auth: ^4.4.1+1
  flutter_html: ^3.0.0-alpha.6
  flutter_image_compress: ^1.1.3
  flutter_inappwebview: ^5.4.4+3
  flutter_jailbreak_detection: ^1.8.0
  flutter_local_notifications: ^8.0.0
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutter_widget_from_html: ^0.8.5
  fluttertoast: ^8.0.9
  formz: ^0.4.1
  gallery_saver: ^2.3.2
  get_it: ^7.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_mobile_ads: ^2.1.0
  google_sign_in: ^5.4.2
  image: ^3.2.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  launch_review: ^3.0.1
  logger: ^1.1.0
  lottie: ^1.4.3
  native_shared_preferences: ^2.0.6
  numberpicker: ^2.1.1
  package_info: ^2.0.2
  palette_generator: ^0.3.3+2
  path_drawing: ^1.0.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.1.0
  photo_view: ^0.14.0
  provider: ^6.0.4
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  rive: ^0.9.1
  rxdart: ^0.27.5
  screenshot: ^1.2.3 #OLD
  scroll_to_index: ^3.0.1
  share: ^2.0.1
  share_extend: ^2.0.0
  share_plus: ^5.0.0
  showcaseview: ^1.1.8
  sign_in_with_apple: ^4.1.0
  simple_gesture_detector: ^0.2.0
  store_redirect: ^2.0.1
  timeline_tile: ^2.0.0
  timezone: ^0.8.0
  tutorial_coach_mark: ^1.2.4
  ua_client_hints: ^1.1.2
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  visibility_detector: ^0.3.3
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.1

dependency_overrides:
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Arista
      fonts:
        - asset: assets/fonts/arista-normal.ttf
          weight: 400
```

### Describe the Bug

I just upgrade flutter 2.8.1 to 3.3.2 and my facebook login error. 

```
E/GeneratedPluginRegistrant: Error registering plugin flutter_facebook_auth, app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin
    The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
        at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
        at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
        at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
        at app.meedu.flutter_facebook_auth.FacebookAuth.<init>(FacebookAuth.java:27)
        at app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin.<init>(FlutterFacebookAuthPlugin.java:20)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:89)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
        at com.example.android.MainActivity.configureFlutterEngine(MainActivity.java:39)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
        at com.example.android.MainActivity.onCreate(MainActivity.java:141)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

After adding `FacebookSdk.sdkInitialize(getApplicationContext());` to my `MainActivity` class. it shows:
```
E/MethodChannel#app.meedu/flutter_facebook_auth: Failed to handle method call
    Log in attempt failed: FacebookActivity could not be started. Please make sure you added FacebookActivity to the AndroidManifest.
        at com.facebook.login.LoginManager.startLogin(LoginManager.kt:1014)
        at com.facebook.login.LoginManager.logIn(LoginManager.kt:746)
        at com.facebook.login.LoginManager.logIn(LoginManager.kt:719)
        at app.meedu.flutter_facebook_auth.FacebookAuth.login(FacebookAuth.java:47)
        at app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin.onMethodCall(FlutterFacebookAuthPlugin.java:42)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
        at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I has follow the guide docs https://facebook.meedu.app/.
It says that i don't need `FacebookActivity` and `CustomTabActivity`.
and i only have to place this in manifest:
`<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />`
`<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`

android/build.gradle
```
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.google.firebase:perf-plugin:1.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

android/app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.firebase.crashlytics'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 33

    lintOptions {
        checkReleaseBuilds false
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.android"
        minSdkVersion 23
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources false
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.android.gms:play-services-analytics:17.0.0'
    implementation 'com.android.installreferrer:installreferrer:1.0'
    implementation "androidx.appcompat:appcompat:1.5.1"
    implementation platform('com.google.firebase:firebase-bom:30.5.0')
    implementation 'com.facebook.android:facebook-android-sdk:15.0.1'
    implementation 'com.facebook.android:facebook-login:15.0.1'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-crashlytics:18.2.13'
    implementation 'com.google.firebase:firebase-analytics:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:23.0.8'
}
```

### Expected Behavior

After upgrading to flutter 3.3.2. I Expect flutter_facebook_auth do not required to use `FacebookActivity` and `CustomTabActivity`.

### To Reproduce

Don't know how to reproduce. I follow the docs https://facebook.meedu.app/ and found nothing wrong.

### flutter doctor -v

```shell
[!] Flutter (Channel unknown, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-ID)
    ! Flutter version 3.3.2 on channel unknown at /Users/username/Development/flutter
    ! Upstream repository unknown
    • Framework revision e3c29ec00c (4 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/username/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/username/Library/Android/Sdk
    • ANDROID_SDK_ROOT = /Users/username/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos         • darwin-x64  • macOS 12.6 21G115 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

### AndroidManifest.xml

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_CALL_LOG" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />

    <uses-permission android:name="android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
    <uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <queries>
        <provider
            android:authorities="com.facebook.katana.provider.PlatformProvider"
            android:exported="false" />
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="sms" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="whatsapp" />
        </intent>
    </queries>

    <application
        android:name="${applicationName}"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:usesCleartextTraffic="true"
        tools:replace="android:allowBackup,icon,label,name"
        tools:node="replace"
        tools:targetApi="m">

        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            tools:replace="android:value"
            android:value="@string/facebook_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            tools:replace="android:value"
            android:value="@string/facebook_client_token"/>
        <meta-data android:name="com.facebook.sdk.AutoInitEnabled"
            android:value="true"/>

        <activity
            android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="signinwithapple" />
                <data android:path="/callback" />
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTask"
            android:theme="@style/LaunchTheme"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:exported="true"
            android:windowSoftInputMode="adjustResize"
            tools:targetApi="n">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="www.example.com" android:pathPrefix="/path"/>
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="*.example.com" android:pathPrefix="/path"/>
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="example" android:host="path"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="delivery_metrics_exported_to_big_query_enabled"
            android:value="true" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/purple" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/channel" />
        <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="false" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />

        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true" />
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/gms_application_id" />

        <meta-data
            android:name="firebase_performance_logcat_enabled"
            android:value="true" />

<!--        <activity-->
<!--            android:name="com.facebook.FacebookActivity"-->
<!--            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"-->
<!--            android:exported="true"-->
<!--            android:label="@string/app_name" />-->
<!--        <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled"-->
<!--            android:value="true"/>>-->
<!--        <meta-data android:name="com.facebook.sdk.AutoInitEnabled"-->
<!--            android:value="true"/>-->

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/gms_version" />

        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:exported="true"
            android:theme="@android:style/Theme.Translucent" />

<!--        <activity-->
<!--            android:name="com.facebook.CustomTabActivity"-->
<!--            android:exported="true">-->
<!--            <intent-filter>-->
<!--                <action android:name="android.intent.action.VIEW" />-->

<!--                <category android:name="android.intent.category.DEFAULT" />-->
<!--                <category android:name="android.intent.category.BROWSABLE" />-->

<!--                <data android:scheme="@string/fb_login_protocol_scheme" />-->
<!--            </intent-filter>-->
<!--        </activity>-->
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:exported="true"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />

        <receiver
            android:name="com.adjust.sdk.AdjustReferrerReceiver"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.google.firebase.components.ComponentDiscoveryService"
            android:directBootAware="true"
            android:exported="true"
            tools:targetApi="n">
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.crashlytics.CrashlyticsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.perf.FirebasePerfRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar"/>
        </service>

        <service
            android:name="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery"
            android:exported="false">
            <meta-data
                android:name="backend:com.google.android.datatransport.cct.CctBackendFactory"
                android:value="cct"/>
        </service>

        <service
            android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" >
        </service>

        <activity
            android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
            android:screenOrientation="portrait"
            android:exported="true"
            android:windowSoftInputMode="stateAlwaysHidden|adjustPan" />

    </application>
</manifest>
```
