### ISSUE TITLE
Can't open Facebook frame

### ISSUE THREAD

**Issue by han-tm** [darwin-morocho/flutter-facebook-auth#297]
### What version are you using?

flutter_facebook_auth: 4.4.1

### What OS and version are you using to local deploy your application?

Android 12

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  cloud_firestore: 3.2.1
  cloud_firestore_platform_interface: 5.5.10
  cloud_firestore_web: 2.6.19
  cloud_functions: 3.3.1
  cloud_functions_platform_interface: 5.1.10
  cloud_functions_web: 4.2.18
  easy_debounce: 2.0.1
  equatable: 2.0.3
  expandable: 5.0.1
  file_picker: 4.5.1
  firebase_auth: 3.4.1
  firebase_auth_platform_interface: 6.3.1
  firebase_auth_web: 3.3.19
  firebase_core: 1.19.1
  firebase_core_platform_interface: 4.4.3
  firebase_core_web: 1.6.6
  firebase_messaging: 11.4.4
  firebase_messaging_platform_interface: 3.5.4
  firebase_messaging_web: 2.4.4
  firebase_storage: 10.3.1
  firebase_storage_platform_interface: 4.1.10
  firebase_analytics: 9.1.12
  firebase_analytics_platform_interface: 3.1.10
  firebase_analytics_web: 0.4.0+17
  # paginate_firestore: ^1.0.3+1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  firebase_storage_web: 3.2.19
  flutter_facebook_auth: 4.4.1
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.1.0
  google_fonts: 3.0.1
  google_sign_in: 5.4.0
  google_sign_in_android: 6.0.1
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  image_picker: 0.8.5+3
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  mime_type: 1.0.0
  page_transition: 2.0.9
  plugin_platform_interface: 2.1.2
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  timeago: 3.2.2
  url_launcher: 6.1.5
  permission_handler: 9.2.0
  geolocator: 8.2.1
  flutter_share: ^2.0.0
  bot_toast: ^4.0.3
  get: ^4.6.5
  # geoflutterfire: ^3.0.3
  # geo_firestore_flutter: ^0.1.5
  # flutter_tindercard: ^0.2.0
  # device_info_plus: ^6.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^1.1.3

dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0

  flutter_test:
    sdk: flutter
```

### Describe the Bug

When I run the function, some window tries to appear and immediately disappears.  Test it on real device with Android 12

### Expected Behavior

Normally the facebook web window should appear

### To Reproduce

```
Future<UserCredential> facebookSignIn() async {
  if (kIsWeb) {
    FacebookAuthProvider facebookProvider = FacebookAuthProvider();

    facebookProvider.addScope('email');
    facebookProvider.setCustomParameters({
      'display': 'popup',
    });

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithPopup(facebookProvider);
  }

  // Trigger the sign-in flow
  final LoginResult loginToken = await FacebookAuth.instance.login();
  final AccessToken? result = loginToken.accessToken;

  // Create a credential from the access token
  final OAuthCredential facebookAuthCredential = FacebookAuthProvider.credential(result!.token);

  // Once signed in, return the UserCredential
  return FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
}

Future<void> signInWithFacebook(BuildContext context) => signInOrCreateAccount(context, facebookSignIn);
```

### Relevant log output

```shell
E/BLASTBufferQueue(32193): [SurfaceView[com.sprestay.siastro/com.sprestay.siastro.MainActivity]#1](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=1
D/libMEOW (32193): meow new tls: 0xb400006e40bc4bc0
D/libMEOW (32193): applied 1 plugins for [com.sprestay.siastro]:
D/libMEOW (32193):   plugin 1: [libMEOW_gift.so]:
D/libMEOW (32193): meow delete tls: 0xb400006e40bc4bc0
D/IS_CTS_MODE(32193): false
D/MULTI_WINDOW_SWITCH_ENABLED(32193): false
D/DecorView[](32193): getWindowModeFromSystem  windowmode is 1
D/ViewRootImpl[FacebookActivity](32193): hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
I/BufferQueueConsumer(32193): [](id:7dc100000002,api:0,p:-1,c:32193) connect: controlledByApp=false
I/BLASTBufferQueue(32193): [ViewRootImpl[FacebookActivity]#2] constructor()
I/BufferQueueProducer(32193): [ViewRootImpl[FacebookActivity]#2(BLAST Consumer)2](id:7dc100000002,api:1,p:32193,c:32193) connect: api=1 producerControlledByApp=true
I/libPerfCtl(32193): fbcNotifySwapBuffers ret=0
D/DecorView[](32193): onWindowFocusChanged hasWindowFocus false
D/DecorView[](32193): onWindowFocusChanged hasWindowFocus false
D/DecorView[](32193): onWindowFocusChanged hasWindowFocus true
I/BufferQueueProducer(32193): [ViewRootImpl[FacebookActivity]#2(BLAST Consumer)2](id:7dc100000002,api:1,p:32193,c:32193) disconnect: api 1
I/BLASTBufferQueue(32193): [ViewRootImpl[FacebookActivity]#2] destructor()
I/BufferQueueConsumer(32193): [ViewRootImpl[FacebookActivity]#2(BLAST Consumer)2](id:7dc100000002,api:0,p:-1,c:32193) disconnect
D/View    (32193): [Warning] assignParent to null: this = DecorView@d6958c1[FacebookActivity]
I/BLASTBufferQueue(32193): releaseBufferCallbackThunk bufferId:138267882160137 framenumber:1 blastBufferQueue is dead
```

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1526], locale ru-RU)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0
```

### AndroidManifest.xml

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.com.com" xmlns:tools="http://schemas.android.com/tools">

    <queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
    </queries>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!-- <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <application android:label="SiAstro" tools:replace="android:label" android:icon="@mipmap/ic_launcher" android:requestLegacyExternalStorage="true">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_si" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorPrimary" />

        <activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data android:name="flutterEmbedding" android:value="2" />


    </application>
</manifest>
```

### MainActivity.kt

```kotlin
package com.com.com

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```
