### ISSUE TITLE
It gives wrong position when you tapping on anywhere on the Arabic app with Arabic Android

### ISSUE THREAD

**Issue by rainlover457** [darwin-morocho/flutter-facebook-auth#298]
### What version are you using?

flutter_facebook_auth: 4.4.1+1

### What OS and version are you using to local deploy your application?

macOS 12.2.1

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: flutterbuyandsell
description: A new Flutter Buy Sell store application.

version: 3.3.0+34
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 
  flutter_facebook_auth: 4.4.1+1
  firebase_core: 1.20.1
  firebase_messaging: 11.0.0
  firebase_database: 7.2.1
  firebase_auth: 3.10.0
  google_mobile_ads: 2.0.1
  fluttertoast: 8.0.9
  video_player: 2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
```

### Describe the Bug

There is something wrong with this dependency when you use it on Arabic app with Arabic Android.

- **The issue is:** You will get a wrong position if you tapping on anywhere on the app. This happens only with Arabic app with Arabic Android, it gives a wrong tapping on position anywhere on the app, but with English Android is working fine.

Here are a video and sample code for this issue:
- **Video for the issue:** https://drive.google.com/file/d/1wsMGfCc4wwr15s-YE4j9R8MyzDDjRhkg

- **Sample code for the issue:** https://drive.google.com/file/d/1nMpZbMPlVT5AqAt6WXFROi3dXXR4Shvc

### Expected Behavior

It should not causing any issues with the tapping on any positions on Arabic app with Arabic Android. There is something wrong with this dependency.

### To Reproduce

**Please Note:** This is just an example, this issue happens when you tapping on anywhere on the app, and this is only happens with Arabic app with Arabic Android and only with this dependency.

- **Video for the issue:** https://drive.google.com/file/d/1wsMGfCc4wwr15s-YE4j9R8MyzDDjRhkg

- **Sample code for the issue:** https://drive.google.com/file/d/1nMpZbMPlVT5AqAt6WXFROi3dXXR4Shvc

- **Please follow these steps:**
 
1.  From your phone settings, change the Android language to Arabic.

2.  Open the app, and tap on the both items, the right side and the left side, you can see it's working fine with English app.

3.  Now tap on the button (Change to Arabic) to change the app language to Arabic, and then tap on the both items, the right side and the left side, you will see that it's not working well in Arabic, if you tapping on the right side it will open the item on the left side instead of the item you have tapped on.

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/pspanaceasoft/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pspanaceasoft/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run path/to/sdkmanager --install "cmdline-tools;latest"
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run flutter doctor --android-licenses to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 5CC895BF-3C25-4B5F-9A98-B3E67B790773 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
