### ISSUE TITLE
No such module 'FBSDKCoreKit'

### ISSUE THREAD

**Issue by Faamica** [darwin-morocho/flutter-facebook-auth#299]
### What version are you using?

4.3.3

### What OS and version are you using to local deploy your application?

Mac 11.3.1

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
version: 1.0.0+24

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1 #3.0.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.0 #^3.1.10
  cloud_functions: ^3.2.9
  cupertino_icons: ^1.0.3
  device_info_plus: ^3.2.4
  file_selector: ^0.8.2+1
  firebase_auth: ^3.0.1
  firebase_core: ^1.20.0 #^1.3.0
  # firebase_database: ^9.0.8
  firebase_messaging: ^11.2.8
  firebase_remote_config: ^2.0.9
  firebase_storage: ^9.0.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^1.3.2
  flutter_spinkit: ^5.1.0
  flutterfire_ui: ^0.4.3+3 #^0.4.2+3
  fluttertoast: ^8.0.7
  google_sign_in: ^5.0.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.3
  iamport_flutter: ^0.10.1+3
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  logger: ^1.0.0
  multi_select_flutter: ^4.1.2 #4.0.0
  package_info_plus: ^1.4.2
  paginate_firestore: 1.0.3+1
  path_provider: ^2.0.2
  photo_view: ^0.13.0
  platform: ^3.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  table_calendar: ^3.0.6
  tutorial_coach_mark: ^1.2.3
  url_launcher: ^6.1.3
  video_player: ^2.2.10
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Katuri
      fonts:
        - asset: fonts/Katuri.otf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

Hi, I am newbie at development and Flutter is my first framework / app.

By the way, I'm not using flutter_facebook_auth package.

But when I run with the iOS simulator, that error happens.

And I suceeded running the app with the real iPhone7. 

How can I solve the error? going crazy ) ;

### Expected Behavior

run in iOS simulator

### To Reproduce

.

### Relevant log output

```shell
^
    /Users/jeonseogchan/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-4.3.3/ios/Classes/FacebookAuth.swift:9:8: error: no such module 'FBSDKCoreKit'
    import FBSDKCoreKit
           ^
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Skipping duplicate build file in Copy Bundle Resources build phase: /Users/jeonseogchan/Downloads/GoogleService-Info.plist (in target 'Runner' from project 'Runner')
    Result bundle written to path:
    	/var/folders/ly/7jxqf41945g08nj820kfkblr0000gn/T/flutter_tools.oX14Og/flutter_ios_build_temp_dirU4ZQ4J/temporary_xcresult_bundle
Swift Compiler Error (Xcode): No such module 'FBSDKCoreKit'
/Users/jeonseogchan/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-4.3.3/ios/Classes/FacebookAuth.swift:8:7

Could not build the application for the simulator.

Error launching application on iPhone 13.
```

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.3.1 20E241 darwin-arm, locale ko-KR)
    • Flutter version 2.10.3 at /Users/jeonseogchan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8달 전), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jeonseogchan/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/jeonseogchan/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • 7EFFD85D-7D5D-44B0-BD7A-8A23B9FEB74C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Info.plist (iOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>ㅇㅇ</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>ㅇㅇ</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>daeng_gu</string>
				<string>com.googleusercontent.apps.177003538036-nifdqr15559eamtu1blsaos7gtu79g9t</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>kakao${native_app_key_here}</string>
		<string>kakaokompassauth</string>
		<string>storykompassauth</string>
		<string>kakaolink</string>
		<string>kakaotalk-5.9.7</string>
		<string>kftc-bankpay</string>
		<string>ispmobile</string>
		<string>itms-apps</string>
		<string>hdcardappcardansimclick</string>
		<string>smhyundaiansimclick</string>
		<string>shinhan-sr-ansimclick</string>
		<string>smshinhanansimclick</string>
		<string>kb-acp</string>
		<string>mpocket.online.ansimclick</string>
		<string>ansimclickscard</string>
		<string>ansimclickipcollect</string>
		<string>vguardstart</string>
		<string>samsungpay</string>
		<string>scardcertiapp</string>
		<string>lottesmartpay</string>
		<string>lotteappcard</string>
		<string>cloudpay</string>
		<string>nhappcardansimclick</string>
		<string>nonghyupcardansimclick</string>
		<string>citispay</string>
		<string>citicardappkr</string>
		<string>citimobileapp</string>
		<string>kakaotalk</string>
		<string>payco</string>
		<string>lpayapp</string>
		<string>hanamopmoasign</string>
		<string>wooripay</string>
		<string>nhallonepayansimclick</string>
		<string>hanawalletmembers</string>
		<string>chaipayment</string>
		<string>kb-auth</string>
		<string>hyundaicardappcardid</string>
		<string>com.wooricard.wcard</string>
		<string>lmslpay</string>
		<string>lguthepay-xpay</string>
		<string>liivbank</string>
		<string>supertoss</string>
		<string>newsmartpib</string>
		<string>mailto</string>
		<string>https</string>
		<string>http</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>사진 등록을 위해 갤러리 접근 권한이 필요해요</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

### Podfile (iOS)

```code
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase'
  # pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  #platform: for KAKAO

  

  

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # The iOS Simulator deployment target 'IPHONES_DEVELOPMENT_TARGET' is set to 8.0~~ 오류나서 
  # https://fomaios.tistory.com/entry/%ED%95%B4%EA%B2%B0%EB%B2%95-%ED%8F%AC%ED%95%A8-The-iOS-Simulator-deployment-target-IPHONESDEVELOPMENTTARGET-is-set-to-80but-the-range-of-suppoted-deployment-target-vesions-is-90-to-14499 여기 보고 설정함
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
   end
  # 여기까지
  end
  
end
```
