### ISSUE TITLE
Can't run the app with version 5.0.1 on iOS 16

### ISSUE THREAD

**Issue by Tom3652** [darwin-morocho/flutter-facebook-auth#302]
### What version are you using?

flutter_facebook_auth: 5.0.1

### What OS and version are you using to local deploy your application?

MacOS 13.0

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: flutter_facebook_auth_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_facebook_auth: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

My iOS app can't run.

I have run the example project as requested to check, even if the given client Token et App ID and it crashes the same way. 

### Expected Behavior

The app should run normally as on flutter_facebook_auth: 4.4.3

### To Reproduce

Run the example project : https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth/example on an iOS 16.1 device. 

### Relevant log output

```shell
On my real app : 


(lldb) dyld[1852]: Symbol not found: _FBLinkable_NSNotificationCenter_NotificationDelivering
  Referenced from: <66419806-6AD3-3599-A5AF-DC1D8A94E700> /private/var/containers/Bundle/Application/9A86F6EF-C7AC-4A7C-A27A-79CA2E0F5C99/Runner.app/Frameworks/FBAEMKit.framework/FBAEMKit
  Expected in:     <2C1FABE1-6807-396C-9F57-A6F7E0C503AE> /private/var/containers/Bundle/Application/9A86F6EF-C7AC-4A7C-A27A-79CA2E0F5C99/Runner.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001e2f74ce0 dyld`__abort_with_payload + 8
dyld`:
->  0x1e2f74ce0 <+8>:  b.lo   0x1e2f74cfc               ; <+36>
    0x1e2f74ce4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1e2f74ce8 <+16>: mov    x29, sp
    0x1e2f74cec <+20>: bl     0x1e2f18de4               ; cerror_nocancel
```

With the example project : 

```
Launching lib/main.dart on Tommy’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XQ67HHZJUC
Running pod install...
Running Xcode build...
Xcode build done.                                           44,2s
Installing and launching...
(lldb) dyld[2330]: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <0BD4548E-B9A5-3D3C-B537-0742E9BF990E> /private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/preboot/Cryptexes/OS@rpath/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/C214B0A2-8925-4DA7-A06B-8661F42E64CA/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache)
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001e2f74ce0 dyld`__abort_with_payload + 8
dyld`:
->  0x1e2f74ce0 <+8>:  b.lo   0x1e2f74cfc               ; <+36>
    0x1e2f74ce4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1e2f74ce8 <+16>: mov    x29, sp
    0x1e2f74cec <+20>: bl     0x1e2f18de4               ; cerror_nocancel
Target 0: (Runner) stopped.
Error launching application on Tommy’s iPhone.
```
```


### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-x64, locale fr-FR)
    • Flutter version 3.3.6 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Tommy’s iPhone (mobile) • 700c28e00d8978a132f439820a90d99c6327a990 • ios            • iOS 16.1 20B82
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Info.plist (iOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Flutter Facebook Auth Example</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>flutter_facebook_auth_example</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb1329834907365798</string>
			</array>
		</dict>
	</array>
	<key>FacebookAppID</key>
	<string>1329834907365798</string>
	<key>FacebookClientToken</key>
	<string>a3227435cff010a782b23acbe1ff174f</string>
	<key>FacebookDisplayName</key>
	<string>Example</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
</dict>
</plist>
```

### Podfile (iOS)

```code
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
