### ISSUE TITLE
mac os login result won't return to app window

### ISSUE THREAD

**Issue by mostafaAbdelazim** [darwin-morocho/flutter-facebook-auth#304]
### What version are you using?

flutter_facebook_auth: ^5.0.1

### What OS and version are you using to local deploy your application?

M1 MBA with  macOS 13.0

### What platforms are you seeing the problem on?

macOS

### pubspec.yaml

```yaml
name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4

  shared_preferences: ^2.0.15
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^5.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
```

### Describe the Bug

After typing in the correct login info in the facebook login window, the result won't return to my app.
Instead, the login window is displaying my facebook home feed page to browse, see screenshots below

<img width="1092" alt="Screenshot 2022-11-06 at 4 55 29 PM" src="https://user-images.githubusercontent.com/43379502/200178538-8c876c52-a7bb-4188-87d5-7bce69812263.png">
<img width="1092" alt="Screenshot_2022-11-06_at_4_51_38_PM" src="https://user-images.githubusercontent.com/43379502/200178542-215d24ae-a5f8-49be-abee-ce24e2eb1663.png">

### Expected Behavior

The login window should close and pass the result back to app window.

### To Reproduce

run a flutter app on mac os 
try to make a login request
do the login process on the facebook login window

### flutter doctor -v

```shell
doctor --verbose
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-EG)
    • Flutter version 3.3.7 on channel stable at /Users/mostafaabdelazim/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (5 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/mostafaabdelazim/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/mostafaabdelazim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/mostafaabdelazim/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

### Info.plist (macOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIconFile</key>
	<string></string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSMinimumSystemVersion</key>
	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>
	<key>NSHumanReadableCopyright</key>
	<string>$(PRODUCT_COPYRIGHT)</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>com.apple.security.network.server</key>
	<true/>
</dict>
</plist>
```
