### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by eav-solution** [darwin-morocho/flutter-facebook-auth#310]
### What version are you using?

5.0.6

### What OS and version are you using to local deploy your application?

MacOS 13

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: perdex
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_tts: ^2.1.0
  tflite_flutter: ^0.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gallery_saver: ^2.3.2
  image: ^3.0.2
  path_provider: ^2.0.1
  image_picker: ^0.8.5+3
  scidart: ^0.0.1-dev.9
  sqflite: ^2.0.2
  ml_linalg: ^13.10.0

  # Firebase
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  firebase_auth: ^4.1.3
  sign_in_with_apple: ^4.2.0
  crypto: ^3.0.2


  # Android
  camera: ^0.8.1+3
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70

  # IOS
#  camera: ^0.9.4+5
#  tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
```

### Describe the Bug

Cannot sign in with facebook.

### Expected Behavior

Login facebook succesful.

### To Reproduce

Future<UserCredential> signInWithFacebook() async {
  // Trigger the sign-in flow
  final LoginResult loginResult = await FacebookAuth.instance.login();

  // Create a credential from the access token
  final OAuthCredential facebookAuthCredential =
      FacebookAuthProvider.credential(loginResult.accessToken.token);

  // Once signed in, return the UserCredential
  return FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
}

### flutter doctor -v

```shell
(tf) lkt@LKT-Macbook ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.0.1 22A400 darwin-arm, locale
    en-VN)
    • Flutter version 3.3.0 on channel stable at
      /Users/lkt/Data/3.Flutter/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lkt/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • M2012K11AG (mobile) • 192.168.1.62:5555 • android-arm64  • Android 12 (API
      31)
    • macOS (desktop)     • macos             • darwin-arm64   • macOS 13.0.1
      22A400 darwin-arm
    • Chrome (web)        • chrome            • web-javascript • Google Chrome
      107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
(tf) lkt@LKT-Macbook ~ %
```

### Info.plist (macOS)

```xml
I can run on ios without issue but android has this problem.
Please help me!
Thanks.
```
