### ISSUE TITLE
can't build iOS

### ISSUE THREAD

**Issue by lucasfcardozo** [darwin-morocho/flutter-facebook-auth#316]
### What version are you using?

flutter_facebook_auth: 5.0.6

### What OS and version are you using to local deploy your application?

macOS m1

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: aff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: 5.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

### Describe the Bug

I just created a new app and added lib `flutter_facebook_auth: 5.0.6`.
when running the command to install the pods, I got this error:
```bash
$ arch -x86_64 pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
  In Podfile:
    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 5.0.4, which depends on
      FBSDKLoginKit (~> 15.1.0)

Specs satisfying the `FBSDKLoginKit (~> 15.1.0)` dependency were found, but they required a higher minimum deployment target.
```

### Expected Behavior

a successful pod installation

### To Reproduce

```bash
$ flutter create new_app
$ cd new_app
$ flutter pub add flutter_facebook_auth:5.0.6
$ flutter clean
$ flutter pub get
$ cd ios
$ arch -x86_64 pod install #for mac m1
```

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-BR)
    • Flutter version 3.3.9 on channel stable at /Users/lucascardozo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lucascardozo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • iPhone 14 (mobile) • DBC41D49-AAD4-4F91-82D5-68349B35EA64 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 13.0.1 22A400 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
