### ISSUE TITLE
No email "identifier" saving in firebase

### ISSUE THREAD

**Issue by erwinagpasa** [darwin-morocho/flutter-facebook-auth#318]
### What version are you using?

flutter_facebook_auth: ^5.0.7

### What OS and version are you using to local deploy your application?

Android

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.4.2
  email_validator: ^2.1.17
  social_login_buttons: ^1.0.7
  font_awesome_flutter: ^10.3.0
  flutter_native_splash: ^2.2.16
  flutter_facebook_auth: ^5.0.7
  cloud_firestore: ^4.3.1
```

### Describe the Bug

No email "identifier" saving in firebase

### Expected Behavior

it should have email saved in firebase

### To Reproduce

n/a

### flutter doctor -v

```shell
n/a
```
