### ISSUE TITLE
Ask for add queries even when I added it

### ISSUE THREAD

**Issue by LeandroMoura3** [darwin-morocho/flutter-facebook-auth#321]
### What version are you using?

5.0.4

### What OS and version are you using to local deploy your application?

win10

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: MCB
description: Aplicativo do Núcleo Comunitário do Brasil

publish_to: "none"

version: 0.5.8+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter_secure_storage: ^7.0.1
  path_provider: ^2.0.10
  youtube_player_iframe: ^3.1.0
  photo_view: ^0.14.0
  mask_text_input_formatter: ^2.3.0
  flutter_svg: ^1.1.0
  url_launcher: ^6.1.3
  package_info_plus: ^1.4.2
  wechat_assets_picker: ^8.1.1
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.1
  flutter_facebook_auth: ^5.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^4.14.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/instagram.svg
    - assets/youtube.svg
```

### Describe the Bug

Even when add the queries to allow Android 30+ communication, show in console the message below and don't work authentication:

Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.

### Expected Behavior

The authentication works.

### To Reproduce

I follow all steps of tutorial, includes the hash key and add MainActivity, but still not working.

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [versÆo 10.0.19044.2364],
    locale pt-BR)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800        
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
```
