### ISSUE TITLE
[Flutter]  Put <meta-data> in <application> makes the apk crash or a black screen.

### ISSUE THREAD

**Issue by JackHuang111** [darwin-morocho/flutter-facebook-auth#323]
### What version are you using?

flutter_facebook_auth ^5.0.6

### What OS and version are you using to local deploy your application?

windows 11

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
dependencies:
  youtube_player_flutter: 8.0.0
  pod_player: ^0.0.5
  firebase_analytics: 9.3.3
  firebase_core: 1.21.1
  firebase_crashlytics: 2.8.9
  firebase_dynamic_links: 4.3.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  flutter_svg:
  url_launcher:
  fluttertoast: ^8.0.8
  flutter_bloc: ^7.2.0
  freezed_annotation: 1.1.0
  flutter_riverpod: ^1.0.3
  get_it: ^7.2.0
  intl: ^0.17.0
  dropdown_button2: 1.4.0
  buttons_tabbar: ^1.3.1
  package_info_plus: ^1.4.2
  flutter_facebook_sdk: ^1.0.0
  percent_indicator: 4.0.0
  flutter_staggered_grid_view: 0.4.0
  share_plus: ^4.0.10
  badges:
  firebase_messaging: ^11.4.1
  flutter_local_notifications: 9.3.1
  google_sign_in: ^5.4.3
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.6
  firebase_auth: ^3.4.2
```

### Describe the Bug

I just follow the document to seting up the file.
https://facebook.meedu.app/docs/5.x.x/android
After that, I run the flutter app and goes crash.

### Expected Behavior

Launch app and login with facebook successfully.

### To Reproduce

according to this document Android configuration
https://facebook.meedu.app/docs/5.x.x/android
```
<application android:label="&#064;string/app_name" ...>
    ...
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
    ...
</application>
```

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.2486], locale zh-TW)
    • Flutter version 2.10.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (9 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at D:\IntelliJ IDEA 2020.2.1
    • Flutter plugin installed
    • Dart plugin version 202.8531

[√] Connected device (4 available)
    • SM A920F (mobile) • 2cd04645851d7ece • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 109.0.1518.55

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### AndroidManifest.xml

```xml
<application
            android:label="*****"
            android:name="${applicationName}"
            android:icon="@mipmap/ic_launcher">
        <meta-data
                android:name="flutterEmbedding"
                android:value="2"/>
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
        <activity
                android:name="com.facebook.FacebookActivity"
                android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
                android:label="@string/app_name"/>
        <activity
                android:name="com.facebook.CustomTabActivity"
                android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="@string/fb_login_protocol_scheme"/>
            </intent-filter>
        </activity>
    </application>
```

### MainActivity.kt

```kotlin
package *****

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```
