### ISSUE TITLE
Developer Policy 6.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.

### ISSUE THREAD

**Issue by BunnyBuddy** [darwin-morocho/flutter-facebook-auth#328]
### What version are you using?

flutter_facebook_auth:^3.5.2

### What OS and version are you using to local deploy your application?

macOS Monterey Version 12.6.3

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: projectX
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# ios
#version: 0.1.25+2

# android
version: 0.1.26+39

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  firebase_core_platform_interface: 4.2.0

dependencies:
  flutter:
    sdk: flutter
#  braintree_device_data:
#    path: ../braintree_device_data
  flutter_braintree:
    path: ./flutter-braintree-master
  onesignal_flutter:
    path: ./flutter-onesignal


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.2
  carousel_slider: ^3.0.0
  email_validator: ^2.0.1
  tab_indicator_styler: ^1.0.0
  flutter_rating_bar:
  flutter_staggered_grid_view: ^0.3.4
  dotted_border: ^2.0.0
  http: ^0.13.1
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0
  google_sign_in: ^5.0.3
  flutter_facebook_auth: ^3.5.2
#  flutter_facebook_auth: ^4.4.1+1
  sign_in_with_apple: ^3.2.0
  sqflite: ^2.0.0+3
  google_place: ^0.4.0
  shared_preferences: ^2.0.6
  nuts_activity_indicator: ^0.1.1
  graphql_flutter: ^5.0.0
#  flutter_braintree: ^2.0.0
  flutter_html: ^2.2.1
  equatable: ^2.0.3
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  image_picker: ^0.8.4+1
#  image_picker: ^0.8.6 // requires gradle to be updated to 7.2 which may break some packages and gradle 7.2 doesn't work with OneSignal
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.3
  firebase_performance: ^0.7.0+9
  url_launcher: ^6.0.10
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_datepicker: ^19.3.45
  flutter_typeahead: ^3.2.1
  lottie: ^1.2.1
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  app_tracking_transparency: ^2.0.2+1
#  new_version: ^0.3.1
  new_version_plus: ^0.0.1+4
  uni_links: ^0.5.1
  app_links: ^2.2.0
  device_info_plus: ^4.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pusher_channels_flutter: ^2.0.1
  intl: ^0.17.0
  social_share: ^2.2.1
  share_plus: ^4.5.3
  upgrader: ^4.7.0
  photo_view: ^0.14.0
  file_picker: ^4.6.1
  flutter_native_splash:
  multi_image_picker2: ^5.0.2
#  cloudflare: ^1.3.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/JSON/
    - assets/JSON/No_Message/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

We have a marketplace app on Playstore as well as Appstore and it was working fine but a few weeks ago we saw a rise in crashes on playstore and then 2 days ago we got an email from Facebook devs which stated as follows (we also tried to reproduce the problem but it works fine on our devices android, iphone, simulator),

Hi,

In order to keep the Meta platform and community safe, we periodically review apps for compliance. We need the following information/action from you on your app, (app name here) Apps (AppId: ***************), in order to approve your app’s continued operation on our platform.

Platforms affected: Android.

Developer Policy 6.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.

During Login, your app is crashing or hanging excessively, creating a broken experience for people trying to use your app. To make sure this flow runs smoothly, check that you've integrated Facebook Login correctly. We recommend that you test Login on all integrations. If you have not already done so, please:

• Here's our quickstart guide for implementing Facebook Login for Android: https://urldefense.proofpoint.com/v2/url?u=https-3A__developers.facebook.com_docs_facebook-2Dlogin_android&d=DwIFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=jXV6E5g3vj8-wl8ry66KEcxbCRCR2tzWnEC5ECG8HUQ&m=o5v5jX4-6ViiW7w9yGMX_UDdcQ3xAbEL-KB-NHvNVMk&s=BT51WiCNKsGTqc6-R9_QPsodMiBYXmUgauwbl9WUv-0&e=
• We encourage you to test your Login integration following these steps here: https://urldefense.proofpoint.com/v2/url?u=https-3A__developers.facebook.com_docs_facebook-2Dlogin_testing-2Dyour-2Dlogin-2Dflow_&d=DwIFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=jXV6E5g3vj8-wl8ry66KEcxbCRCR2tzWnEC5ECG8HUQ&m=o5v5jX4-6ViiW7w9yGMX_UDdcQ3xAbEL-KB-NHvNVMk&s=repKnHooOaayaEusd1czyytm2TBoduY0lTXzZ7E9U-I&e=
• Best Practices for Login can be found here: https://urldefense.proofpoint.com/v2/url?u=https-3A__developers.facebook.com_docs_facebook-2Dlogin_best-2Dpractices&d=DwIFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=jXV6E5g3vj8-wl8ry66KEcxbCRCR2tzWnEC5ECG8HUQ&m=o5v5jX4-6ViiW7w9yGMX_UDdcQ3xAbEL-KB-NHvNVMk&s=3ZJ-XGX_uXwMaTkpUBjGv97uFX1vVNATByxqX8SgO_M&e=

Please reply to this email with the requested information/change request before 2023-03-06 03:00:00 PST. 

You can request up to two extensions if you need additional time to gather information.

Follow this link to securely submit any requested credentials: https://urldefense.proofpoint.com/v2/url?u=https-3A__developers.facebook.com_apps_917887418904610_re-2Dreview_&d=DwIFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=jXV6E5g3vj8-wl8ry66KEcxbCRCR2tzWnEC5ECG8HUQ&m=o5v5jX4-6ViiW7w9yGMX_UDdcQ3xAbEL-KB-NHvNVMk&s=HmM5_eEhE7kMRr0l-dlLx9G7sMKAlkqHz5ljqdu6ih8&e=  

To ensure that we receive your response:
  - Email us from the contact email registered in App Dashboard.
  - Respond directly to this email and include our email in the “To” field.
  - Do not change the subject line or include any additional emails in the "cc" field.

If we do not receive a response from you, your app will be subject to enforcement. 

Thank you for your cooperation in our continued efforts to keep our platform safe,

Meta Developer Operations Team

### Expected Behavior

A few weeks ago it was working fine. I don't know what happened or what changed on facebook that lead to this issue, kindly let me know of a possible solution or way around this.
Thankyou.

### To Reproduce

This is the function that's being called upon login or signup with Facebook.

Future signInWithFacebook() async {
    Map<String, dynamic> _userData;
    AccessToken _accessToken;
    // loginBehavior is only supported for Android devices, for ios it will be ignored
    final result = await FacebookAuth.instance.login(
      loginBehavior: LoginBehavior.dialogOnly, // (only android) show an authentication dialog instead of redirecting to facebook app
    );
    switch (result.status) {
      case LoginStatus.success:
        _accessToken = result.accessToken;
final userData = await FacebookAuth.instance.getUserData();

        _userData = userData;

        if (_userData.isNotEmpty) {

          Map<String, dynamic> data = {
            "accessToken": _accessToken.token,
            "expiry": _accessToken.expires.microsecondsSinceEpoch,
            "id": _userData['id'],
            "name": _userData['name'],
            "email": _userData['email'],
            "platform": Platform.isIOS ? "ios" : "android",
          };

          LoginUserModel userModel = await registerWithFacebook(payload: data);
          if (userModel.token != null) {
            SocialModel model = SocialModel(
              displayName: _userData['name'],
              email: _userData['email'],
              id: userModel.customer.id,
              authToken: userModel.token,
            );
            return model;
          } else {
            return SocialModel();
          }
        }
        return SocialModel();
        break;
      case LoginStatus.cancelled:

        Get.back();
        AlertWidgets.showErrorBar(msg: "Cancelled By User", bottom: true);
        break;
      case LoginStatus.failed:
        Get.back();
        AlertWidgets.showErrorBar(msg: "Error Login with Facebook", bottom: true);
        break;
      case LoginStatus.operationInProgress:
        break;
    }
}

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6.3 21G419 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/macbookpro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • Infinix X6811 (mobile) • 07363251BU000513 • android-arm64  • Android 11 (API 30)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### AndroidManifest.xml

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="***************">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
   <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        tools:replace="android:label"
        android:requestLegacyExternalStorage="true"
       >
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleInstance"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"

            >
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <!-- Deep linking -->
            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" android:host="********.page.link" />
                <data android:scheme="https" />
            </intent-filter>
            <!-- Deep linking with ********* -->
<!--            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />-->
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" android:host="www.***********.com" />
                <data android:scheme="https" />
            </intent-filter>
        </activity>
        <!--Facebook-->
       <meta-data android:name="com.facebook.sdk.ApplicationId"
           android:value="@string/facebook_app_id"/>
       <meta-data android:name="com.facebook.sdk.ClientToken"
           android:value="@string/facebook_client_token"/>
       <provider
           android:name="com.facebook.FacebookContentProvider"
           android:authorities="com.facebook.app.FacebookContentProvider[facebook_app_id]"
           android:exported="false" />
       <activity android:name="com.facebook.FacebookActivity"
           android:configChanges=
               "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
           android:label="@string/app_name"/>
       <activity
           android:name="com.facebook.CustomTabActivity"
           android:exported="true">
           <intent-filter>
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               <data android:scheme="@string/fb_login_protocol_scheme" />
           </intent-filter>
       </activity>
       <!--braintree-->
       <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
           android:exported="true"
           android:launchMode="singleTask">
           <intent-filter>
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               <data android:scheme="${applicationId}.braintree" />
           </intent-filter>
       </activity>
       <!-- Don't delete the meta-data below.
            This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
       <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
       <provider
           android:name="androidx.core.content.FileProvider"
           android:authorities="${applicationId}.com.shekarmudaliyar.social_share"
           android:exported="false"
           android:grantUriPermissions="true"
           tools:replace="android:authorities">
           <meta-data
               android:name="android.support.FILE_PROVIDER_PATHS"
               android:resource="@xml/filepaths" />
       </provider>
<!--       <meta-data-->
<!--           android:name="firebase_performance_logcat_enabled"-->
<!--           android:value="true" />-->
   </application>
</manifest>
```
