### ISSUE TITLE
getApplicationDocumentsDirectory from path_provider stops working

### ISSUE THREAD

**Issue by Jamminroot** [darwin-morocho/flutter-facebook-auth#35]
**Describe the bug**
Hello,

when I specify `path_provider` explicitly in `pubspec.yaml`, it's method `getApplicationDocumentsDirectory` stops working when there's `flutter-facebook-auth` provided already.

**Environment**
Add your `flutter doctor -v`
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DChichuk\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\DChichuk\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\DChichuk\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\DChichuk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • SM G986B (mobile) • 192.168.0.254:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Add both deps to pubspec.yaml:

```yml
  path_provider: ^1.6.24
  flutter_facebook_auth: ^1.0.2
```
Try to call getApplicationDocumentsDirectory() from `path_provider` package.
Get exception with method not found meaning.

**Expected behavior**
getApplicationDocumentsDirectory() works.

Did not provide FULL description just because I worked this around already by removing `path_provider` from `pubspec.yaml` (added implicitly anyway), and just to bring this to your sight.
Feel free to delete otherwise.

**Comment by Jamminroot** [comment]
Exception message:
```
E/flutter ( 7716): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 7716): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
```
And no, it is not resolved, unfortunately.

**Comment by darwin-morocho** [comment]
> MissingPluginException

Hi @Jamminroot  I couldn't  reproduce the bug. Please add your complete `pubspec.yaml`.
And your code.

Alo you can check the next [repo](https://github.com/meedu-app/flutter-facebook-login-example.git) I've added the path_provider dependency and every works. Clone these repo and change your facebook credentials and let me Know if the error persists

**Comment by Jamminroot** [comment]
Cheers!
Still trying to nail down the problem. I _might_ have mistakenly came to conclusion it's in flutter_facebook_auth because disabling it did affect the way the app works.
Can't really provide the code, but here's a list of dependencies:
```
environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  cupertino_icons: ^0.1.3
  html: ^0.14.0+4
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  cached_network_image: ^2.3.3
  octo_image: ^0.3.0
  sqflite: ^1.3.2+1
  palette_generator: ^0.2.3
  network_to_file_image: ^2.3.6
  path_provider: ^1.6.24
  http_client_helper: ^0.2.1
  extended_image:
    path: ../extended_image/
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  google_fonts: ^1.1.1
  simple_animations: ^2.3.1
```

Sorry that I can't really provide more than that.
Other suspect I currently try to triage is `google_fonts` - might be dependencies incompatibility of some sort (I think they reference `path_provider` v 1.4.0).

I'll close the issue for now, and will loop back in case the proble actually is in your plugin.

Sorry for taking your time o/
