### ISSUE TITLE
Package does not work in release mode 

### ISSUE THREAD

**Issue by Muhammad-Rehab** [darwin-morocho/flutter-facebook-auth#353]
### What version are you using?

flutter_facebook_auth: ^5.0.7

### What OS and version are you using to local deploy your application?

windows 11

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.5.5+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.0.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^7.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.4.0+5
  flutter_typeahead: ^4.6.1
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
#  universal_html: ^2.2.2
  flutter_inappwebview: ^5.7.1+2
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number: ^1.0.0
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
  google_sign_in: ^6.1.4
  google_sign_in_web: ^0.12.0
  flutter_facebook_auth: ^5.0.0
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: ^6.3.0
  custom_map_markers: ^0.0.2+1
  image_compression_flutter: ^1.0.2
  fwfh_text_style: ^2.22.8+1
  card_swiper: ^2.0.4
  expandable_bottom_sheet: ^1.1.1+1
  uni_links: ^0.5.1
  modal_bottom_sheet:
  sign_in_with_apple: ^4.3.0
  flutter_html: ^3.0.0-alpha.5
  flutter_widget_from_html: 0.10.1
  intl: ^0.17.0
  firebase_auth: ^4.6.3
  device_preview: ^1.1.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
```

### Describe the Bug

I tried to log in with facebook and the package work correctly in debug mode bud it does not work in release mode. 

### Expected Behavior

I want my Flutter app to detect Facebook account information and log in automatically to my app by Facebook account.

### To Reproduce

![Screenshot 2023-07-14 110003](https://github.com/darwin-morocho/flutter-facebook-auth/assets/65614150/62e0744a-b728-441c-86ed-91542252d7f2)
![Screenshot 2023-07-14 110135](https://github.com/darwin-morocho/flutter-facebook-auth/assets/65614150/c5df3155-f2c5-4e22-9d0f-0897f39f372f)
![Screenshot 2023-07-14 110213](https://github.com/darwin-morocho/flutter-facebook-auth/assets/65614150/672d5b2d-2c7d-462f-a132-87686b752c3b)

### flutter doctor -v

```shell
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
    • Flutter version 3.7.10 on channel stable at C:\Users\moham\Downloads\Compressed\flutter_windows_3.7.10-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 months ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\moham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 114.0.1823.79

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
