### ISSUE TITLE
ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL does not contain the email 

### ISSUE THREAD

**Issue by dayerdl** [darwin-morocho/flutter-facebook-auth#362]
### What version are you using?

6.0.2

### What OS and version are you using to local deploy your application?

macOS 12.6.6

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: Growth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  provider: ^6.0.0
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  firebase_ui_firestore: ^1.5.11
  firebase_storage: ^11.0.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.8.0
  intl: ^0.18.0
  fl_chart: ^0.63.0
  event_bus: 2.0.0
  chewie: ^1.2.0
  video_player: ^2.7.1
  google_fonts: ^5.1.0
  numberpicker: ^2.1.2
  path_provider: ^2.0.5
  csv: ^5.0.2
  cached_network_image: ^3.2.3
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  flutter_svg: ^2.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - images/
    - assets/
    - assets/icon/
    - assets/male_3830.csv
    - 180_classics/
```

### Describe the Bug

I am logging with Facebook auth a user which previously was logged with Google. This produces an error of ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL where i am expecting to have the email which is already registered.
I debug the code and i can see that the exception contains the email on the details. However when the exception reaches the method 'platformExceptionToFirebaseAuthException' in the class exception.dart the email gets lost. And is because fromPigeon = true. Becasue i can see afterwards how the email is parsed properly. How can i prevent this from happening?

![image](https://github.com/darwin-morocho/flutter-facebook-auth/assets/1933760/7a54a459-e0ec-491a-9c74-df0bde277809)

### Expected Behavior

I would expect to receive the email on the error so i can check for which providers this email is attached to

### To Reproduce

1. Login with google.
2. Try to login with Facebook. I would like to execute this code:
final providers =
        await FirebaseAuth.instance.fetchSignInMethodsForEmail(email);
        if (providers.contains(Constants.googleCom)) {
          await loginWithGoogle();
          FirebaseAuth.instance.currentUser?.linkWithCredential(credential);
        }

### flutter doctor -v

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.6 21G646 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
