### ISSUE TITLE
Logint Sucee,but FacebookAuth.instance.accessToken null 

### ISSUE THREAD

**Issue by Lanticee** [darwin-morocho/flutter-facebook-auth#369]
### What version are you using?

6.0.2

### What OS and version are you using to local deploy your application?

macos 14.1.1

### What platforms are you seeing the problem on?

macOS

### pubspec.yaml

```yaml
platforms:
  android:
  ios:
  macos:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  camera_macos: ^0.0.7+2
  camera_windows: ^0.2.1+8
  chewie: ^1.7.1
  comment_box: ^0.0.18
  cupertino_icons: ^1.0.5
  decimal: ^2.3.3
  desktop_window: ^0.4.0
  dio: ^5.3.2
  ffmpeg_kit_flutter_full_gpl: 6.0.3
  file_picker: ^5.3.3
  firebase_auth: ^4.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1
  open_filex: ^4.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.0
  video_player: ^2.8.1
  video_player_media_kit: ^1.0.4
```

### Describe the Bug

Login to Facebook is sucess, and get return correct, but at 14.1.1 ,FacebookAuth.instance.accessToken get null, 
it works at macos before version.

### Expected Behavior

FacebookAuth.instance.accessToken work before, if i need get information.

### To Reproduce

I just follow
Future<UserCredential> signInWithFacebook() async {
  // Trigger the sign-in flow
  final LoginResult loginResult = await FacebookAuth.instance.login();

  // Create a credential from the access token
  final OAuthCredential facebookAuthCredential = FacebookAuthProvider.credential(loginResult.accessToken.token);

  // Once signed in, return the UserCredential
  return FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
}

then 
FacebookAuth.instance.accessToken to get information to check expires

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale
    zh-Hant-TW)
    • Flutter version 3.16.0 on channel stable at
      /Users/lanticet/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/lanticet/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
