### ISSUE TITLE
Facebook SDK is not updating in developer console. How can i fix this ?

### ISSUE THREAD

**Issue by Kliff-techonologies** [darwin-morocho/flutter-facebook-auth#381]
### What version are you using?

flutter_facebook_auth: ^6.0.3

### What OS and version are you using to local deploy your application?

Latest versions

### What platforms are you seeing the problem on?

Android, iOS

### pubspec.yaml

```yaml
name: cheezoo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# 
version: 1.0.134+166

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0 # for State management
  # the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^5.0.0
  cupertino_icons: ^1.0.5
  material_design_icons_flutter: ^6.0.7096
  flutter_bloc: ^7.2.0
  http: ^1.0.0
  shared_preferences: ^2.1.1
  badges: ^3.1.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
#  flutter_apns: ^1.6.0
#  flutter_apns_x:
#    git:
#      url: https://github.com/Mono
#      ref: main
  firebase_messaging: ^14.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.0.3
  flutter_local_notifications: ^14.0.0+2
# twitter_login: ^3.0.5
  sms_autofill: ^2.2.0
  geolocator:
  geocoding: ^2.1.0
  curved_navigation_bar: ^1.0.1
  #share_plus: ^7.0.0
  share_plus:
    git:
      url: https://github.com/Monojit12/share_plus.git
      ref: main
  #file_picker: ^5.2.6
  #image_picker: ^0.8.7+4
  wechat_assets_picker: ^8.5.0
  flutter_image_compress: ^2.0.3
  video_player: ^2.6.1
  #video_thumbnail: ^0.4.3
  dio: ^5.1.2
  sendbird_sdk: ^3.2.18
  intl: ^0.18.1
  flutter_launcher_icons:
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.0.0
  photo_view: ^0.14.0
  syncfusion_flutter_sliders: ^21.2.4
  timezone: ^0.9.0
  extended_image: ^8.1.1
  #gallery_saver: ^2.3.2
  gallery_saver:
    git:
      url: https://github.com/Monojit12/gallery_saver.git
      ref: master
  calendar_view: ^1.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.5.0
  country_picker: ^2.0.12
  otp_text_field: ^1.1.2
  multi_select_flutter: ^4.0.0
  flutter_simple_multiselect: ^2.0.0
  dotted_border: ^2.0.0
  permission_handler: ^10.2.0
  intl_phone_field: ^3.1.0
  image_cropper: ^5.0.0
  #watch_connectivity: ^0.1.5
  watch_connectivity: 0.1.4+1
  #open_mail_app: ^0.4.5
  pin_code_fields: ^7.4.0
  connectivity_plus: ^4.0.1
  bot_toast: ^4.0.3
# flutter_native_text_input: ^2.4.0
  mime: ^1.0.4
  in_app_purchase: ^3.1.8
  #flutter_screenutil: ^5.8.2
  firebase_crashlytics: ^3.3.1
  flutter_branch_sdk: ^6.9.0
  #dart_code_metrics: ^5.6.0
  #flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground : "assets/ic_adaptive_react.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/sendbird/
    - assets/weatherblack/
    - assets/weatherwhite/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
       - asset: assets/font/Nunito-Light.ttf
         weight: 200
       - asset: assets/font/Nunito-Regular.ttf
         weight: 500
       - asset: assets/font/Nunito-Medium.ttf
         weight: 700
       - asset: assets/font/Nunito-Medium.ttf
         weight: 900



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

![image (5)](https://github.com/darwin-morocho/flutter-facebook-auth/assets/121100245/9e40f9d9-fe3d-497e-b6c8-332416f1ef76)

### Expected Behavior

want to show correct sdk in facebook console

### To Reproduce

nothing

### flutter doctor -v

```shell
-----
```
