### ISSUE TITLE
Facebook SDK is not updating in developer console. How can i fix this ?

### ISSUE THREAD

**Issue by Namanjain12** [darwin-morocho/flutter-facebook-auth#382]
### What version are you using?

flutter_facebook_auth: ^6.0.3

### What OS and version are you using to local deploy your application?

Latest versions

### What platforms are you seeing the problem on?

Android, iOS

### pubspec.yaml

```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0 # for State management
  # the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^5.0.0
  cupertino_icons: ^1.0.5
  material_design_icons_flutter: ^6.0.7096
  flutter_bloc: ^7.2.0
  http: ^1.0.0
  shared_preferences: ^2.1.1
  badges: ^3.1.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
#  flutter_apns: ^1.6.0
#  flutter_apns_x:
#    git:
#      url: https://github.com/xyz.git
#      ref: main
  firebase_messaging: ^14.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.0.3
  flutter_local_notifications: ^14.0.0+2
# twitter_login: ^3.0.5
  sms_autofill: ^2.2.0
  geolocator:
  geocoding: ^2.1.0
  curved_navigation_bar: ^1.0.1
  #share_plus: ^7.0.0
  share_plus:
    git:
      url: https://github.com/xyz.git
      ref: main
  #file_picker: ^5.2.6
  #image_picker: ^0.8.7+4
  wechat_assets_picker: ^8.5.0
  flutter_image_compress: ^2.0.3
  video_player: ^2.6.1
  #video_thumbnail: ^0.4.3
  dio: ^5.1.2
  sendbird_sdk: ^3.2.18
  intl: ^0.18.1
  flutter_launcher_icons:
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.0.0
  photo_view: ^0.14.0
  syncfusion_flutter_sliders: ^21.2.4
  timezone: ^0.9.0
  extended_image: ^8.1.1
  #gallery_saver: ^2.3.2
  gallery_saver:
    git:
      url: https://github.com/xyz.git
      ref: master
  calendar_view: ^1.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.5.0
  country_picker: ^2.0.12
  otp_text_field: ^1.1.2
  multi_select_flutter: ^4.0.0
  flutter_simple_multiselect: ^2.0.0
  dotted_border: ^2.0.0
  permission_handler: ^10.2.0
  intl_phone_field: ^3.1.0
  image_cropper: ^5.0.0
  #watch_connectivity: ^0.1.5
  watch_connectivity: 0.1.4+1
  #open_mail_app: ^0.4.5
  pin_code_fields: ^7.4.0
  connectivity_plus: ^4.0.1
  bot_toast: ^4.0.3
# flutter_native_text_input: ^2.4.0
  mime: ^1.0.4
  in_app_purchase: ^3.1.8
  #flutter_screenutil: ^5.8.2
  firebase_crashlytics: ^3.3.1
  flutter_branch_sdk: ^6.9.0
```

### Describe the Bug

![image (5)](https://github.com/darwin-morocho/flutter-facebook-auth/assets/65751884/a4f35129-d94b-4a29-9297-7e996898ed09)

### Expected Behavior

It should have to show correct version of facebook sdk on facebook console.

### To Reproduce

-----

### flutter doctor -v

```shell
------
```
