### ISSUE TITLE
facebook account cache - logout, clear cache

### ISSUE THREAD

**Issue by nokia6290** [darwin-morocho/flutter-facebook-auth#386]
### What version are you using?

6.04

### What OS and version are you using to local deploy your application?

iOS/Android latest versions

### What platforms are you seeing the problem on?

Android, iOS

### pubspec.yaml

```yaml
# Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.6
  firebase_storage: ^11.5.1
  firebase_crashlytics: ^3.4.4
  firebase_analytics: ^10.7.0
  cloud_firestore: ^4.13.1
  firebase_remote_config: ^4.3.4
  firebase_dynamic_links: ^5.4.4
  cloud_functions: ^4.5.4

  # Auth
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.1.6
  apple_sign_in_safety: ^0.0.6

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  google_place: ^0.4.7 #Discontinued package
  dio: ^5.4.0
  geolocator: ^10.1.0


  # Notifications
  flutter_local_notifications: ^16.3.2

  # app dependencies
  go_router: ^13.0.0
  another_xlider: ^3.0.1
  delayed_display: ^2.0.0
  flutter_native_image: ^0.0.6+1
  flutter_rating_bar: ^4.0.1
  flutter_reorderable_grid_view: ^4.0.0
  reorderable_grid_view: ^2.2.7
  flutter_svg: ^2.0.9
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  string_validator: ^1.0.2
  transparent_image: ^2.0.1
  unsplash_client: ^2.1.1
  uuid: ^4.2.1

  cached_network_image: ^3.3.0
  maps_launcher: ^2.2.0
  lottie: ^2.6.0
  flutter_native_splash: ^2.3.5
  dotted_border: ^2.1.0
  package_info_plus: ^4.2.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  grouped_list: ^5.1.2
  flutter_slidable: ^3.0.1
  jiffy: ^6.2.1
  path_provider: ^2.1.1
  cloudinary_url_gen: ^1.3.0
  url_launcher: ^6.1.14
  amplitude_flutter: ^3.16.1
  app_settings: ^5.1.1
  internet_connection_checker: ^1.0.0+1
  flutter_phoenix: ^1.1.1
  flutter_animate: ^4.2.0+1
  wakelock_plus: ^1.1.3
  flutter_app_badger: ^1.5.0
  gap: ^3.0.1
  settings_bundle: ^0.0.1

  #  Forms
  reactive_forms: ^16.1.1
  reactive_phone_form_field: ^2.0.1
  phone_numbers_parser:
  reactive_pinput: ^3.0.0
  pinput:
  scrolls_to_top: ^2.1.1
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  flutter_dotenv: ^5.1.0

  # UI
  shimmer: ^3.0.0

  # Background Task
  workmanager: ^0.5.2



dev_dependencies:
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
```

### Describe the Bug

Cannot choose another account for facebook authentication.

Tried removing the app from facebook page (when user has options to deauth all apps he ever connected)
Uninstall app, reinstall fresh app
Logout from facebook auth and firebase auth
removed facebook user from firebase and custom backend.

launched fb for live production.

Cannot allow the user to select to change facebook account and try login.

### Expected Behavior

Allow user to select if he wants to use another facebook account

### To Reproduce

Difficult to reproduce. Its a setup that works, but does not allow to change facebook account.

### Relevant log output

```shell
Receiving no exception or log during this process.
```

### flutter doctor -v

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B74 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone (78). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```
