### ISSUE TITLE
Classic login is not available on IOS

### ISSUE THREAD

**Issue by rebindev** [darwin-morocho/flutter-facebook-auth#396]
### What version are you using?

6.2.0

### What OS and version are you using to local deploy your application?

ios 14

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: facebook_bot_flutter
description: The most advanced facebook bot.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+0

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  flutter_facebook_auth: ^6.2.0


  my_flutter_package:
    git:
      url: git@github.com:rebindev/my_flutter_package.git
  blueprint_system:
    git:
      url: git@github.com:rebindev/blueprint_system.git
  font_awesome_flutter: ^10.7.0
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0
  video_player: ^2.8.4
  file_picker: ^8.0.0+1
  #file_icon: ^1.0.0
  audioplayers: ^6.0.0
  custom_refresh_indicator: ^3.1.0
  record: ^5.0.5
  app_settings: ^5.1.1
  #  flutter_animate: ^4.5.0
  #  glass: ^2.0.0+1
  #      path: bboks/book
  #      ref: main




  path: any
  flutter_svg: ^2.0.10+1
  intl: any
  device_frame: ^1.1.0
#  icons_plus: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #  fonts:
  #    - family: NizarNastaliqKurdish
  #      fonts:
  #        - asset: fonts/NizarNastaliqKurdish.ttf
  #    - family: Roboto-Light
  #      fonts:
  #        - asset: fonts/Roboto-Light.ttf
  assets:
    - assets/
    - assets/questions.svg



flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_splash_android.png
  #  branding: assets/logo.png
  color_dark: "#191919"
  image_dark: assets/logo_splash_android.png
  #  branding_dark: assets/logo.png

  android_12:
    image: assets/logo_splash_android.png
    #    icon_background_color: "#ffffff"
    image_dark: assets/logo_splash_android.png
  #    icon_background_color_dark: "#121212"

  web: false
  ios: false
  android: true
#  dart run flutter_native_splash:create
```

### Describe the Bug

Hello, today i update the package and when i login it uses limited login. I need classic login as i need business permissions which are not available on limitted login. please add an option to enable classic login

### Expected Behavior

i expect to be able to change default login to either classic or to limited manually.

### To Reproduce

just login on IOS.

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.3.1 23D60 darwin-arm64, locale en-IQ)
    • Flutter version 3.19.5 on channel stable at /Users/rebinali/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rebinali/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Rebin's iPhone (mobile) • 00008101-000A1018266A001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
