### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider))

### ISSUE THREAD

**Issue by onurc4kir** [darwin-morocho/flutter-facebook-auth#40]
I'm getting this error on android when run my app. I've already tried flutter clean and update some packages to latest version. 

I wasn't getting this error when it stopped working on the project 2-3 weeks ago.

`MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`
**Edit:** Error is getting out when I remove `flutter_facebook_auth: ^1.0.2+2` package.
**Edit 2:** I created new flutter app with same packages and It is working without error. 
Packages that I use.

```
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  #cupertino_icons: ^1.0.0

  google_fonts: ^1.1.1
  provider: ^4.3.2+2
  #page transition animation
  page_transition: '^1.1.7+2'
  #for some UI elements not very essential
  flui: 0.9.2
  #ios style date picker
  flutter_datetime_picker: ^1.4.0
  get_it: ^5.0.1
  #Height, age, range slider
  flutter_xlider: ^3.4.0
  #For picking image from gallery
  image_picker: ^0.6.7+12
  image_pickers: ^1.0.8+7

  #For reading icons at flutter
  flutter_svg: ^0.19.1
  flutter_icons: ^1.1.0

  #For showing loading icon when provider state changes
  loading_overlay: ^0.2.1
  flutter_styled_toast: ^1.4.0+1
  #Firebase Packages
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.2+2
  #firebase_database: ^4.4.0

  #maps and geolocation packages Using At MapPage
  google_maps_flutter: ^1.0.6
  google_place: ^0.3.3
  #getting user current location.
  geolocator: ^6.1.4

  #cluster manager for Google Maps. Using at MapPage
  google_maps_cluster_manager: ^0.2.0

  #to make bottom container for map Using at MapPage
  sliding_up_panel: ^1.0.2
  #To get LatLng from an address or to get Address From an LatLng
  geocoder: ^0.2.1

  #For swipe cards
  swipe_stack: ^1.0.0

  #For creating timing indicator at match and likes page. Look at circular avatars
  percent_indicator: ^2.1.8

  #to make location search based on geohash.
  geoflutterfire: ^2.2.1

  #for local data managment. Key value pairs
  shared_preferences: ^0.5.12+4
  #cache image and loading indicator fo them
  cached_network_image: ^2.4.1

  #to draw chart. Used at venue detail page.
  fl_chart: ^0.12.0

  # Create unique id for firebase documents
  uuid: ^2.2.2

  path_provider: ^1.6.24
  #some stream operations do
  rxdart: ^0.24.1
  #Google recaptcha plugin
  flutter_recaptcha_v2: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

Runtime log
```
E/flutter (12424): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (12424): <asynchronous suspension>
E/flutter (12424): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (12424): #2      MethodChannelPathProvider.getApplicationSupportPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:38:26)
E/flutter (12424): #3      getApplicationSupportDirectory (package:path_provider/path_provider.dart:73:39)
E/flutter (12424): #4      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:28:27)
E/flutter (12424): #5      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:33:22)
E/flutter (12424): #6      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:7:22)
E/flutter (12424): #7      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:244:15)
E/flutter (12424): <asynchronous suspension>
E/flutter (12424): #8      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:162:18)
E/flutter (12424): <asynchronous suspension>
E/flutter (12424): #9      googleFontsTextStyle (package:google_fonts/src/google_fonts_base.dart:107:3)
E/flutter (12424): #10     GoogleFonts.arimo (package:google_fonts/google_fonts.dart:7910:12)
E/flutter (12424): #11     MyApp.build.<anonymous closure> (package:spott/main.dart:57:37)
E/flutter (12424): #12     new MultiProvider.<anonymous closure> (package:provider/src/provider.dart:121:48)
E/flutter (12424): #13     Builder.build (package:flutter/src/widgets/basic.dart:7183:48)
E/flutter (12424): #14     StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
E/flutter (12424): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
E/flutter (12424): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (12424): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (12424): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (12424): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (12424): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (12424): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (12424): #22     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
E/flutter (12424): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (12424): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (12424): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (12424): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (12424): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (12424): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (12424): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (12424): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (12424): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (12424): #32     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
E/flutter (12424): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (12424): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (12424): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (12424): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (12424): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (12424): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (12424): #39     _NestedHookElement.mount (package:nested/nested.dart:188:11)
E/flutter (12424): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (12424): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (12424): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (12424): #43     Element.rebuild (package:flutter/src/widgets/framewor
```
