### ISSUE TITLE
It will always be LoginStatus.cancelled.

### ISSUE THREAD

**Issue by ttb-inc** [darwin-morocho/flutter-facebook-auth#406]
### What version are you using?

flutter_facebook_auth: 7.0.0

### What OS and version are you using to local deploy your application?

macOS Somoma 14.4.1

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: ttb_auth
description: A new Flutter package.
version: 0.0.1
homepage: ''
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_facebook_auth: 7.0.0          # https://pub.dev/packages/flutter_facebook_auth/versions

  google_sign_in: 6.2.1                 # https://pub.dev/packages/google_sign_in/versions

  firebase_auth: 4.19.5                  # https://pub.dev/packages/firebase_auth/versions

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter

  flutter_lints: 4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/translations/

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

It will always be LoginStatus.cancelled.
This was normal in previous versions.

```
      /// firebase user
      LoginResult response = await FacebookAuth.instance.login();
```

flutter_facebook_auth: 7.0.0
![스크린샷 2024-05-20 오후 12 25 30](https://github.com/darwin-morocho/flutter-facebook-auth/assets/59724931/1cdd2a3e-1f0a-4c7b-8806-5cd4c2c10964)

flutter_facebook_auth: 6.2.0
![스크린샷 2024-05-20 오후 12 35 48](https://github.com/darwin-morocho/flutter-facebook-auth/assets/59724931/a7702709-1606-4cdb-9223-cf2f4aa3449f)

Thank you.

### Expected Behavior

...

### To Reproduce

...

### flutter doctor -v

```shell
/Users/jeonglockpark/Desktop/work/flutter_sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale ko-KR)
    • Flutter version 3.22.0 on channel stable at /Users/jeonglockpark/Desktop/work/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (11 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jeonglockpark/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0
```
