### ISSUE TITLE
Login always fails on iOS 

### ISSUE THREAD

**Issue by petodavid** [darwin-morocho/flutter-facebook-auth#413]
### What version are you using?

7.0.0

### What OS and version are you using to local deploy your application?

macOS 14.5

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.1.4
  multiple_result: ^5.1.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  firebase_performance: ^0.10.0+1
  easy_localization: ^3.0.7
  get_it: ^7.7.0
  flutter_animate: ^4.5.0
  introduction_screen: ^3.1.14
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  flutter_keyboard_visibility: ^6.0.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.0
  adaptive_dialog: ^2.1.0
  flutter_svg: ^2.0.10+1
  infinite_scroll_pagination: ^4.0.0
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  dropdown_search: ^5.0.6
  onesignal_flutter: ^5.2.0
  rive: ^0.13.7
  gap: ^3.0.1
  flutter_vibrate: ^1.3.0
  gms_check: ^1.0.2
  flutter_tabler_icons: ^1.29.0
  dotted_border: ^2.1.0
  slide_countdown: ^1.6.1
  smooth_page_indicator: ^1.1.0
  sliver_tools: ^0.2.12
  map_launcher: ^3.3.1
  share_plus: ^9.0.0
  collection: ^1.18.0
  vector_math: ^2.1.4
  json_annotation: ^4.9.0
  toastification: ^2.0.0
  flutter_inappwebview: ^6.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  crypto: ^3.0.3
  barcode_widget: ^2.0.4
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  mobile_scanner: ^5.1.1
  easy_debounce: ^2.0.3
  provider: ^6.1.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
```

### Describe the Bug

FacebookAuth.instance.login is always cancelled on iOS when production **published** live Facebook app is used with an account that is not part of the Facebook developer account. 

`email` and `public_profile` permissions are enabled

### Expected Behavior

`loginResult.status == LoginStatus.success` should be true on iOS too, just like on Android

### To Reproduce

```
try {
   final rawNonce = generateNonce();
   final nonce = sha256ofString(rawNonce);
   final loginResult = await FacebookAuth.instance.login(loginTracking: LoginTracking.limited, nonce: nonce);
   if (loginResult.status == LoginStatus.success) {
     final token = loginResult.accessToken?.tokenString;
     if (token == null) return Error(FacebookSignInFailure());
     late OAuthCredential facebookAuthCredential;
     if (loginResult.accessToken is LimitedToken) {
       facebookAuthCredential = OAuthProvider('facebook.com').credential(idToken: token, rawNonce: rawNonce);
     } else {
       facebookAuthCredential = FacebookAuthProvider.credential(token);
     }
     await firebaseAuth.signInWithCredential(facebookAuthCredential);
     return currentUser(reload: true);
   }
   debugPrint(loginResult.message);
   return Error(FacebookSignInFailure());
 } on FirebaseAuthException catch (e) {
   debugPrintStack(stackTrace: e.stackTrace, label: e.toString());
   return Error(FacebookSignInFailure());
 } catch (e) {
   debugPrint(e.toString());
   return Error(FacebookSignInFailure());
 }
```

### flutter doctor -v

```shell
Last login: Thu Jun 13 08:21:50 on console
┌ david@Davids-MacBook-Pro-3  ~  | 08:35:13
└$ flutter doctor -v
[!] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/david/Developer/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.4.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/david/Developer/flutter. Consider adding
      /Users/david/Developer/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (7 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.80
    ! Error: Browsing on the local area network for Dávid’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

┌ david@Davids-MacBook-Pro-3  ~  | 08:35:27
└$
```

### Info.plist (iOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>tsc</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>FacebookAppID</key>
	<string>$(facebookAppId)</string>
	<key>FacebookClientToken</key>
	<string>$(facebookClientToken)</string>
	<key>FacebookDisplayName</key>
	<string>$(APP_DISPLAY_NAME)</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string></string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb$(facebookAppId)</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>comgooglemaps</string>
		<string>iosamap</string>
		<string>waze</string>
		<string>here-location</string>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>mailto</string>
		<string>https</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>$(LAUNCH_SCREEN_STORYBOARD)</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarHidden</key>
	<false/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>NSCameraUsageDescription</key>
	<string>This app needs camera access to scan QR codes</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Your location is required for more accurate notifications.</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>hu</string>
		<string>sr-Latn</string>
	</array>
</dict>
</plist>
```

### Podfile (iOS)

```code
# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end
```
