### ISSUE TITLE
Login fails on iOS PlatformException(FAILED, The operation couldn’t be completed. (com.facebook.sdk.core error 8.), null, null)

### ISSUE THREAD

**Issue by DavidHajum** [darwin-morocho/flutter-facebook-auth#417]
### What version are you using?

7.1.1

### What OS and version are you using to local deploy your application?

macOS 15.5

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Getx
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.27.2
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.9.0
  firebase_remote_config: ^4.3.19

  # Socials
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1

  # Modals and popups
  modal_bottom_sheet: ^3.0.0-pre
  adaptive_dialog: ^2.1.0
  flutter_platform_alert: ^0.5.1
  toastification: ^1.2.1

  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  custom_check_box: ^0.0.4
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  font_awesome_flutter:
  flutter_html: ^3.0.0-beta.2
  jovial_svg: ^1.1.20
  flutter_spinkit: ^5.2.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.0.0
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  infinite_scroll_pagination: ^4.0.0
  app_tracking_transparency: ^2.0.4
  package_info_plus: ^4.0.2
  version: ^3.0.2
  store_redirect: ^2.0.2
  cached_network_image: ^3.3.1
  easy_localization: ^3.0.5
  image_picker: ^1.1.0
  file_picker: ^8.0.1
  flutter_avif: ^2.3.0
  flutter_keyboard_visibility: ^6.0.0
  timezone: ^0.9.2
  expand_tap_area: ^1.1.1
  scroll_to_index: ^3.0.1
  rive: ^0.13.7
  app_settings: ^5.1.1
  permission_handler: ^11.3.0
  flutter_quill: ^9.4.6
  flutter_quill_extensions: ^9.4.6
  vsc_quill_delta_to_html: ^1.0.3
  animated_page_transition:
    git: https://github.com/DavidHajum/animated_page_transition.git
  dots_indicator: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_phoenix: ^1.1.1
  feather_icons_svg:
    git:
      url: "https://github.com/FrazeColder/feather_icons_svg"
  dotted_border: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_verification_code: ^1.1.7
  app_links: ^5.0.0
  app_badge_plus: ^1.0.0
  flutter_widget_from_html: ^0.15.1
  html: ^0.15.4
  flutter_lightbox: ^0.1.3
  flutter_slidable: ^3.1.1

  cupertino_icons: ^1.0.6

dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
```

### Describe the Bug

I get this error, when I try to log in on iOS:

PlatformException(FAILED, The operation couldn’t be completed. (com.facebook.sdk.core error 8.), null, null)

I followed [this](https://facebook.meedu.app/docs/7.x.x/ios) instruction for the setup and tried [this](https://stackoverflow.com/a/75347987/17129385) suggestion on StackOverflow, but no luck so far.

My code currently looks like this:

    final LoginResult result = await FacebookAuth.instance.login();
    final userData = await FacebookAuth.instance.getUserData();

    if (result.accessToken != null) {
      do more stuff ...

The login functionality works without problems on Android.

I'm using a test account to log in.

### Expected Behavior

The login function returns normally

### To Reproduce

Make a login call

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-DE)
    • Flutter version 3.22.2 on channel stable at /Users/david/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (7 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/david/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Users/david/Desktop/setups/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • iPhone 15 (mobile)              • 39C4731E-F868-4097-BFC0-3A0BA258AA72 • ios          •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 14.5 23F79 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```
