### ISSUE TITLE
flutter_facebook_auth_web: web 1.0.0 dependency

### ISSUE THREAD

**Issue by mrnusa** [darwin-morocho/flutter-facebook-auth#424]
### What version are you using?

6.1.1

### What OS and version are you using to local deploy your application?

Flutter 3.24.1

### What platforms are you seeing the problem on?

Android, iOS

### pubspec.yaml

```yaml
version: 1.0.61+212
environment: 
  sdk: '>=3.1.1 <4.0.0'
dependencies: 
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10
  http: ^1.2.2
  image: ^4.2.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  provider: ^6.1.2
  dartz: ^0.10.1
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  map_launcher: ^3.5.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  linkedin_login: ^3.0.5
  sign_in_with_apple: ^6.1.2
  dio: ^5.6.0
  modal_progress_hud_nsn: ^0.5.1
  get: ^4.6.6
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  image_cropper: '^8.0.2'
  expandable: ^5.0.1
  package_info_plus: ^8.0.2
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.2.0
  cloud_functions: ^5.1.0
  flutter_local_notifications: ^17.2.2
  uni_links: ^0.5.1
  supercharged: ^2.1.1
  photo_view: ^0.15.0
  badges: ^3.1.2
  timeago: ^3.7.0
  flutter_device_type: ^0.4.0
  qr_code_scanner: ^1.0.1
  fuzzy: ^0.5.1
  webview_flutter: ^4.9.0
  google_sign_in: ^6.2.1
  flutter_platform_widgets: ^7.0.1
  email_validator: ^3.0.0
  flutter_linkify: '^6.0.0'
  direct_select_flutter: ^1.1.1
  move_to_background: ^1.0.2
  jwt_decoder: ^2.0.1
  flutter_facebook_auth: ^7.1.0
  geocoding: ^3.0.0
  flutter_chat_ui: ^1.6.15
  flutter_notification_channel: ^3.1.0
  infinite_scroll_pagination: ^4.0.0
  #https://pub.dev/packages/new_version

  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


flutter: 
  assets: 
    - assets/translations/
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts: 
    - 
      family: Roboto
      fonts: 
        - 
          asset: assets/fonts/Roboto-Regular.ttf
        - 
          asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - 
          asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - 
          asset: assets/fonts/Roboto-Italic.ttf
          style: italic
  uses-material-design: true
flutter_icons: 
  image_path_ios: assets/launcher/icon_ios.png
  image_path_android: assets/launcher/icon_android.png
  adaptive_icon_background: assets/launcher/background.png
  adaptive_icon_foreground: assets/launcher/foreground.png
  ios: true
  android: true
flutter_native_splash: 
  image: assets/splash/splash.png
  color: '#FD5402'
  android_disable_fullscreen: true
  fullscreen: true
```

### Describe the Bug

try to use the latest cached_network_image: (3.4.1) that depends to web 1.0 with flutter_facebook_auth: ^7.1.0 that depends web on 0.5.1
Please upgrade flutter_facebook_auth_web web package dependency to 1.0.0

### Expected Behavior

flutter pub get runs without error

### To Reproduce

try to use the latest cached_network_image: (3.4.1) that depends to web 1.0 with flutter_facebook_auth: ^7.1.0 that depends web on 0.5.1

### flutter doctor -v

```shell
[!] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-HU)
    • Flutter version 3.24.1 on channel stable at /Users/*/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (10 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/*/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • *
    • *
    • *

[✓] Network resources
    • All expected network resources are available.
```
