### ISSUE TITLE
Limited login problem on ios only

### ISSUE THREAD

**Issue by aakashx58** [darwin-morocho/flutter-facebook-auth#428]
### What version are you using?

  flutter_facebook_auth: ^7.1.1

### What OS and version are you using to local deploy your application?

MacOS 14.6.1

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: tokma
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^1.1.5
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  file_picker: ^8.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.3.0
  flutter_quill: ^9.3.11
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^14.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  heroicons_flutter: ^0.3.0
  intl: ^0.19.0
  pretty_dio_logger: ^1.4.0
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
```

### Describe the Bug

![IMG_9935](https://github.com/user-attachments/assets/427e39b2-f187-459a-8379-fd5917d662f2)

### Expected Behavior

import 'package:flutter/material.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';

class FacebookAuthService {
  AccessToken? _accessToken;
  Map<String, dynamic>? _userData;

  AccessToken? get accessToken => _accessToken;
  Map<String, dynamic>? get userData => _userData;

  /// Check if the user is logged in and fetch user data if available
  Future<void> checkIfLoggedIn() async {
    final accessToken = await FacebookAuth.instance.accessToken;
    if (accessToken != null) {
      debugPrint('AccessToken: $accessToken');
      _accessToken = accessToken;
      _userData = await FacebookAuth.instance.getUserData();
      debugPrint('UserData: $_userData');
      debugPrint("code: ${accessToken.tokenString}");
    }
  }

  /// Login to Facebook and fetch user data
  Future<LoginResult> login() async {
    final LoginResult result = await FacebookAuth.instance.login(
      permissions: [
        'public_profile',
        'email'
      ], // Add more permissions if needed
    );
    if (result.status == LoginStatus.success) {
      final AccessToken accessToken = result.accessToken!;
      debugPrint('AccessToken: $accessToken');
      _accessToken = accessToken;
      _userData = await FacebookAuth.instance.getUserData();
      debugPrint('UserData: $_userData');
    } else {
      debugPrint('Login failed: ${result.status}, ${result.message}');
    }
    return result;
  }

  /// Log out from Facebook
  Future<void> logout() async {
    await FacebookAuth.instance.logOut();
    debugPrint('Logged out from Facebook');
    _accessToken = null;
    _userData = null;
  }
}

### To Reproduce

access token: Instaance of limited token

### Relevant log output

```shell
getting access token as accesstoken: Instance of limited tokem
```

### flutter doctor -v

```shell
Aakash@MB-PRO tokma-mobile % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-x64, locale en-US)
    • Flutter version 3.22.3 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (9 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/pratimatamang/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • B8A9539C-94A9-458C-AAA4-B6265C86D24D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 14.6.1 23G93 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources                
    • All expected network resources are available.

• No issues found!
```

### Info.plist (iOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Dargakan</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>dargakan</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbxxxx</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FacebookAppID</key>
	<string>xxx</string>
	<key>FacebookClientToken</key>
	<string>xxx</string>
	<key>FacebookDisplayName</key>
	<string>Dargakan</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSMicrophoneUsageDescription</key>
	<string>The plugins use the microphone access.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarHidden</key>
	<false/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
</dict>
</plist>
```
