### ISSUE TITLE
can not upload new update of my app on xcode 16 received error contain bicode

### ISSUE THREAD

**Issue by Mohamedzaky252** [darwin-morocho/flutter-facebook-auth#430]
### What version are you using?

  flutter_facebook_auth: ^4.4.0+1

### What OS and version are you using to local deploy your application?

  flutter_facebook_auth: ^4.4.0+1

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.51+78

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_theme: 3.3.0
  animated_bottom_navigation_bar: ^1.2.0
  awesome_notifications: 0.7.4+1
  banner_carousel: ^1.2.1
  basic_utils: ^3.9.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  chewie: ^1.5.0
  cloud_firestore: ^4.14.0
  contained_tab_bar_view: ^0.8.0
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.5
  currency_formatter: ^2.0.1
  custom_clippers: ^2.0.0
  custom_faqs:
    git:
      url: https://github.com/ambrosethebuild/custom_faqs
      ref: main
  custom_sliding_segmented_control: 1.7.5
  dartx: ^1.1.0
  device_info_plus: ^9.1.2
  dio: ^4.0.6
  dio_http_cache_lts: ^0.4.0
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  double_back_to_close: ^2.0.0
  dynamic_height_grid_view: ^0.0.3
  easy_refresh: ^3.4.0
  equatable: ^2.0.3
  eva_icons_flutter: ^3.1.0
  expand_widget: ^2.1.0
  firebase_auth: ^5.3.0
  firebase_crashlytics: ^4.1.2
  firebase_dynamic_links: ^6.0.7
  firebase_messaging: ^15.1.2
  firestore_chat: ^0.1.2
  # fl_location: ^3.0.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_dropdown_alert: ^1.0.7
  flutter_facebook_auth: ^4.4.0+1
  flutter_form_builder: 9.0.0
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^4.3.7
  geohash_plus: ^1.1.1
  geolocator: ^10.1.0
  glass: ^1.0.1+1
  glass_kit: 3.0.0
  google_fonts: 5.1.0
  google_maps_flutter: ^2.3.1
  google_maps_place_picker_mb: ^3.1.2
  google_nav_bar: ^5.0.6
  google_places_flutter: ^2.0.5
  google_sign_in: ^5.3.3
  group_radio_button: 1.2.0
  http: ^1.0.0
  hugeicons: ^0.0.7
  image_picker: 1.0.0
  in_app_review: ^2.0.4
  inspection: ^0.0.13
  jiffy: ^5.0.0
  keyboard_dismisser: ^3.0.0
  localize_and_translate: ^4.1.1
  location: ^5.0.3
  map_launcher: ^2.2.3
  maps_toolkit: ^2.0.1
  masonry_grid: ^1.0.0
  measure_size: ^3.0.1
  package_info_plus: ^4.0.2
  permission_handler: ^11.3.0
  pin_code_fields: ^8.0.1
  pinch_zoom: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh_flutter3: ^2.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  quickalert: ^1.1.0
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  share: ^2.0.4
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^4.0.0
  singleton: ^0.0.3-nullsafety
  slide_countdown: ^0.2.8
  sliding_up_panel: ^2.0.0+1
  sliver_snap: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  spider: ^4.2.2
  stacked: 3.4.0
  sticky_headers: ^0.3.0+2
  supercharged: ^2.1.1
  synchronized: ^3.0.1
  timelines: ^0.1.0
  upgrader: 7.1.0
  url_launcher: ^6.3.0
  velocity_x: ^4.2.1
  what3words: ^3.1.0

dependency_overrides:
  archive: ^3.6.1
  cloud_firestore: ^5.4.2
  flutter_widget_from_html: ^0.10.1
  firebase_core: ^3.5.0
  intl: ^0.18.1
  http: ^0.13.0
  # win32: ^5.0.0
  win32: ^5.5.4
  webview_flutter_android: 3.16.1
  url_launcher_ios: ^6.3.1
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

dev_dependencies:
  flutter_application_id: ^2.0.0-dev
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  translator: ^0.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#5e17eb"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/anim/
    - assets/images/icons/
    - assets/json/
    - assets/lang/
    - assets/
```

### Describe the Bug

Asset validation failed

Invalid Executable. The executable 'Runner.app/Frameworks/FBAEMKit.framework/FBAEMKit' contains bitcode. (ID: 5c806ec7-2b8f-4ba7-a798-7a465a9aec8c)

Asset validation failed

Invalid Executable. The executable 'Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode. (ID: 793d6c5b-96d8-4870-a21a-f8e0c5321f4e)

Asset validation failed

Invalid Executable. The executable 'Runner.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode. (ID: ef59c9a9-027d-438b-b49b-e93021e52c36)

Asset validation failed

Invalid Executable. The executable 'Runner.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode. (ID: 56b3fd70-9d6c-433f-8687-fc4f02398072)

received this error after archive app and upload it to apple

this is my podfile

Uncomment this line to define a global platform for your project
platform :ios, '14.0'

CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
'Debug' => :debug,
'Profile' => :release,
'Release' => :release,
}

def flutter_root
generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), FILE)
unless File.exist?(generated_xcode_build_settings_path)
raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
end

File.foreach(generated_xcode_build_settings_path) do |line|
matches = line.match(/FLUTTER_ROOT=(.*)/)
return matches[1].strip if matches
end
raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
use_frameworks!
use_modular_headers!

Override Firebase SDK Version
$FirebaseSDKVersion = '10.22.0'
flutter_install_all_ios_pods File.dirname(File.realpath(FILE))
end

post_install do |installer|
installer.generated_projects.each do |project|
project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
end
end
end
installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
end
installer.pods_project.targets.each do |target|
if target.name == 'BoringSSL-GRPC'
target.source_build_phase.files.each do |file|
if file.settings && file.settings['COMPILER_FLAGS']
flags = file.settings['COMPILER_FLAGS'].split
flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
file.settings['COMPILER_FLAGS'] = flags.join(' ')
end
end
end
end
installer.pods_project.targets.each do |target|
flutter_additional_ios_build_settings(target)

target.build_configurations.each do |config|

You can remove unused permissions here
for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',

## dart: PermissionGroup.camera
'PERMISSION_CAMERA=1',

## dart: PermissionGroup.microphone
'PERMISSION_MICROPHONE=1',

## dart: PermissionGroup.photos
'PERMISSION_PHOTOS=1',

##
## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
'PERMISSION_LOCATION=1',

## dart: PermissionGroup.notification
'PERMISSION_NOTIFICATIONS=1',
]

end
end
end
<img width="1000" alt="Screenshot 1446-04-09 at 11 50 04 PM" src="https://github.com/user-attachments/assets/e51ba09c-3a07-48ce-a456-02e2ddf93526">

### Expected Behavior

when. trying upload new update to apple

### To Reproduce

when. trying upload new update to apple

### flutter doctor -v

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-x64, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### Podfile (iOS)

```code
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Override Firebase SDK Version
  # $FirebaseSDKVersion = '10.22.0'
    
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
  end
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## The 'PERMISSION_LOCATION' macro enables the `locationWhenInUse` and `locationAlways` permission. If
        ## the application only requires `locationWhenInUse`, only specify the `PERMISSION_LOCATION_WHENINUSE`
        ## macro.
        ##
        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

      ]

    end
  end
end
```
