### ISSUE TITLE
Error installing FBAEMKit when running pod install --repo-update

### ISSUE THREAD

**Issue by ablbol** [darwin-morocho/flutter-facebook-auth#433]
### What version are you using?

flutter_facebook_auth:^7.0.1

### What OS and version are you using to local deploy your application?

macOS 14.6.1 (23G93)

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
version: 1.6.4+64
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.22.3

dependencies:
  android_id: ^0.4.0
  audio_waveforms: ^1.0.5
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dotted_border: ^2.1.0
  firebase_analytics: ^11.1.0
  firebase_app_check: ^0.3.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_database: ^11.0.2
  firebase_messaging: ^15.0.2
  firebase_remote_config: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_ui_firestore: ^1.6.4
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^7.0.1
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.39
  mask_text_input_formatter: ^2.9.0
  material_design_icons_flutter: ^7.0.7296
  open_mail_app: ^0.4.5
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  purchases_flutter: ^6.29.4
  rate_my_app: ^2.2.0
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  showcaseview: ^3.0.0
  stack_trace: ^1.11.1
  store_redirect: ^2.0.2
  swipe_to: ^1.0.6
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/envs/
    - assets/email_icons/
    - assets/flags/
    - assets/images/
    - assets/json/
    - assets/social_icons/
  fonts:
    - family: OolfaIcons
      fonts:
        - asset: fonts/OolfaIcons.ttf
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
```

### Describe the Bug

When running the command "pod install --repo-update", I get the following error:

```
[!] Error installing FBAEMKit
[!] /usr/bin/curl -f -L -o /var/folders/d3/_70rxq2n6n5djk4nt7rrpdk80000gn/T/d20241025-24366-1tnqsne/file.zip https://github.com/facebook/facebook-ios-sdk/releases/download/v17.0.3/FacebookSDK_Dynamic.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 98 30.2M   98 29.7M    0     0  38310      0  0:13:48  0:13:34  0:00:14 47982
curl: (56) Recv failure: Connection reset by peer
```

### Expected Behavior

I expect the "pod install --repo-update" command to run without errors.

### To Reproduce

Run the following command:

```
pod install --repo-update
```

### flutter doctor -v

```shell
[!] Flutter (Channel [user-branch], 3.22.3, on macOS 14.6.1 23G93 darwin-x64, locale
    en-AE)
    ! Flutter version 3.22.3 on channel [user-branch] at
      /Users/aimnblbol/Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official
      channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision b0850beeb2 (3 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aimnblbol/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/aimnblbol/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • LYA L29 (mobile)       • LHS7N19116023078          • android-arm64  • Android 10
      (API 29)
    • SM A546E (mobile)      • RZCWC0498LT               • android-arm64  • Android 14
      (API 34)
    • Aimn’s iPhone (mobile) • 00008120-001E48962283C01E • ios            • iOS 17.6.1
      21G93
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 14.6.1
      23G93 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Info.plist (iOS)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>CADisableMinimumFrameDurationOnPhone</key>
		<true />
		<key>CFBundleDevelopmentRegion</key>
		<string>$(DEVELOPMENT_LANGUAGE)</string>
		<key>CFBundleDisplayName</key>
		<string>$(FLAVOR_APP_NAME)</string>
		<key>CFBundleExecutable</key>
		<string>$(EXECUTABLE_NAME)</string>
		<key>CFBundleIdentifier</key>
		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
		<key>CFBundleInfoDictionaryVersion</key>
		<string>6.0</string>
		<key>CFBundleLocalizations</key>
		<array>
			<string>en</string>
			<string>es</string>
		</array>
		<key>CFBundleName</key>
		<string>$(FLAVOR_APP_NAME)</string>
		<key>CFBundlePackageType</key>
		<string>APPL</string>
		<key>CFBundleShortVersionString</key>
		<string>$(FLUTTER_BUILD_NAME)</string>
		<key>CFBundleSignature</key>
		<string>????</string>
		<key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>$(GOOGLE_SERVICE_REVERSED_CLIENT_ID)</string>
					<string>fb$(FACEBOOK_APP_ID)</string>
				</array>
			</dict>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLName</key>
				<string>Bundle Id</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
				</array>
			</dict>
		</array>
		<key>CFBundleVersion</key>
		<string>$(FLUTTER_BUILD_NUMBER)</string>
		<key>FacebookAppID</key>
		<string>$(FACEBOOK_APP_ID)</string>
		<key>FacebookClientToken</key>
		<string>$(FACEBOOK_CLIENT_TOKEN)</string>
		<key>FacebookDisplayName</key>
		<string>$(FLAVOR_APP_NAME)</string>
		<key>LSApplicationQueriesSchemes</key>
		<array>
			<string>fbapi</string>
			<string>fb-messenger-share-api</string>
			<string>googlegmail</string>
			<string>x-dispatch</string>
			<string>readdle-spark</string>
			<string>airmail</string>
			<string>ms-outlook</string>
			<string>ymail</string>
			<string>fastmail</string>
			<string>superhuman</string>
			<string>protonmail</string>
		</array>
		<key>LSRequiresIPhoneOS</key>
		<true />
		<key>UIBackgroundModes</key>
		<array>
			<string>fetch</string>
			<string>remote-notification</string>
		</array>
		<key>UILaunchStoryboardName</key>
		<string>LaunchScreen</string>
		<key>UIMainStoryboardFile</key>
		<string>Main</string>
		<key>UISupportedInterfaceOrientations</key>
		<array>
			<string>UIInterfaceOrientationPortrait</string>
		</array>
		<key>UIViewControllerBasedStatusBarAppearance</key>
		<false />
		<key>FirebaseDeepLinkPasteboardRetrievalEnabled</key>
		<string>NO</string>
		<key>NSPhotoLibraryUsageDescription</key>
		<string>Allow photos access</string>
		<key>NSCameraUsageDescription</key>
		<string>Allow camera access</string>
		<key>NSBluetoothAlwaysUsageDescription</key>
		<string>Allow Bluetooth Access</string>
		<key>NSBluetoothPeripheralUsageDescription</key>
		<string>Allow Bluetooth peripheral Access</string>
		<key>NSCalendarsUsageDescription</key>
		<string>Allow Calender Access</string>
		<key>NSContactsUsageDescription</key>
		<string>Allow Contact Access</string>
		<key>NSLocationWhenInUseUsageDescription</key>
		<string>Oolfa needs access to location when open.</string>
		<key>NSMotionUsageDescription</key>
		<string>Allow Motion Access</string>
		<key>NSSpeechRecognitionUsageDescription</key>
		<string>Allow Speech Recognition Access</string>
		<key>UIApplicationSupportsIndirectInputEvents</key>
		<true />
		<key>NSMicrophoneUsageDescription</key>
		<string>Allow mic access</string>
		<key>NSAppleMusicUsageDescription</key>
		<string>Oolfa needs to play chat audio messages</string>
		<key>NSAppTransportSecurity</key>
		<dict>
			<key>NSAllowsArbitraryLoads</key>
			<true />
		</dict>
		<key>FlutterDeepLinkingEnabled</key>
		<true />
	</dict>
</plist>
```

### Podfile (iOS)

```code
# Uncomment this line to define a global platform for your project
platform :ios, '13'
#$FirebaseSDKVersion = '10.22.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # pod 'FirebaseFirestore/WithLeveldb', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.18.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      ##
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
      ##
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',        
      ]
    end
  end
end
```
