### ISSUE TITLE
Facebook Policy violation: Privacy and Terms links in the Oauth popup do not work

### ISSUE THREAD

**Issue by giorgio79** [darwin-morocho/flutter-facebook-auth#444]
### What version are you using?

7.1.1

### What OS and version are you using to local deploy your application?

Android

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: ....
description: A new Flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.ßßß
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.3.82+362

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #flutter_facebook_image_picker:
  #  git:
  #    url: https://github.com/restra-social/flutter_facebook_image_picker
  #    ref: master
  #    publish_to: none

  #  location_picker_flutter_map:
  #    git:
  #      url: https://github.com/giorgio79/location_picker_flutter_map
  #      ref: main
  #      publish_to: none

  google_maps_place_picker_mb:
    git:
      url: https://github.com/giorgio79/google_maps_place_picker_mb
      ref: master
      publish_to: none

  nordigen_integration:
    git:
      url: https://github.com/giorgio79/nordigen_integration
      ref: main
      publish_to: none

  flutter_icons:
    git:
      url: https://github.com/giorgio79/flutter-icons.git
      ref: master
      publish_to: none

  geoflutterfire:
    git:
      url: https://github.com/giorgio79/geoflutterfire
      ref: master
      publish_to: none

  geocoder2:
    git:
      url: https://github.com/giorgio79/geocoder2
      ref: main
      publish_to: none

  weekday_selector: # Temporary solution awaiting the release of a new version including the following PR: https://github.com/smaho-engineering/weekday_selector/pull/12
    git:
      url: https://github.com/smaho-engineering/weekday_selector.git
      ref: e9c604a8cabb04ea3a169c3379c270c59810e4b0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #app_tracking_transparency: ^2.0.3
  #background_location: ^0.0.9+1
  #catcher: ^0.4.0
  #csv: ^4.0.3
  #diffutil_sliverlist: ^0.5.1
  #facebook_app_events: ^0.8.2
  #ff_navigation_bar: ^0.1.4
  #firebase_core_platform_interface: ^3.0.1
  #firebase_performance: ^0.9.3+2
  #fluid_slider: ^1.0.1
  #flutter_auth_buttons: ^0.6.0
  #flutter_chat: ^0.1.5
  #flutter_custom_slider: ^0.0.4
  #flutter_lwa: ^0.2.0
  #flutter_share: ^1.0.2+1
  #flutter_signin_button: ^2.0.0
  #flutter_touch_spin: ^1.0.0
  #geocoder2: ^1.4.0
  #geoflutterfire: ^3.0.1
  #google_map_polyline: ^0.2.0+1
  #google_maps_place_picker_mb: ^3.1.2
  #https://firebase.flutter.dev/docs/auth/social
  #iban_form_field: ^0.2.1
  #international_phone_input: ^1.0.3
  #json_diff: ^0.2.1
  #nordigen_integration: ^1.7.6
  #observable: ^0.22.2
  #pattern_formatter: ^2.0.0
  #permission_handler: ^5.0.1+1
  #persistent_bottom_nav_bar: any
  #plaid_flutter: ^2.1.3
  #provider: ^5.0.0
  #rxdart: ^0.27.1
  #search_map_place: ^0.3.0
  #searchable_dropdown: ^1.1.3
  #shared_preferences: ^0.5.8
  #sliding_up_panel: ^1.0.2
  #spinner_input: ^0.1.2
  #animated_list_plus: ^0.5.2
  #cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.2
  #country_pickers: ^3.0.1
  crypto: ^3.0.6
  #cupertino_icons: ^1.0.8
  duration: ^4.0.3
  #email_validator: ^3.0.0
  firebase_analytics: ^11.4.1
  #firebase_app_check: ^0.3.2+1
  firebase_auth: ^5.4.1
  #firebase_auth_web: ^5.13.7
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  #firebase_dynamic_links: ^6.1.1
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_facebook_auth: ^7.1.1
  flutter_firebase_chat_core: ^1.6.8
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  #flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  glob: ^2.1.3
  #google_geocoding_api: ^1.5.2
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.14.12
  google_maps_flutter_platform_interface: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  google_mobile_ads: ^5.3.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  #image_picker: ^1.1.2
  #implicitly_animated_list: ^2.3.0
  in_app_purchase: ^3.2.1
  #in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.21
  in_app_review: ^2.0.10
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  #latlong2: ^0.9.1
  logger: ^2.5.0
  #mime: ^2.0.0
  mobile_number: ^3.0.0
  numberpicker: ^2.1.2
  open_route_service: ^1.2.7
  #path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  #provider: ^6.1.2
  #rating_dialog: ^2.0.4
  rxdart: ^0.28.0
  search_choices: ^2.3.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.1
  sign_button: ^2.0.6
  sign_in_with_apple: ^6.1.4
  simple_icons: ^10.1.3
  translations_cleaner: ^0.0.5
  url_launcher: ^6.3.1
  #place_picker_google: ^0.0.14
  #typewritertext: ^3.0.9
  webp: ^1.0.0+1
  app_links: ^6.3.3
  uuid: ^4.5.1

#dependency_overrides:
#  google_maps_flutter:
#    git:
#      url: https://github.com/lukaskurz/plugins
#      path: packages/google_maps_flutter/google_maps_flutter
#      ref: main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "lib/images/icon-ios.png"
  image_path_android: "lib/images/icon-android.png"

dev_dependencies:
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  dependency_validator: ^5.0.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  very_good_analysis: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- path: assets/
    - path: lib/images/
    - path: lib/images/currency/
    - path: lib/models/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

The Privacy Policy and Terms of Service links are not working in the OAuth popup. Facebook just raised this issue and maybe others are getting it. The links are correctly configured in the app dashboard on Facebook.

![Image](https://github.com/user-attachments/assets/b9b8b8b3-09a4-4b33-bb86-e4c8fa35eb51)

### Expected Behavior

Link should open in a new browser window? Instead I am taken back to the app with an error.

### To Reproduce

Click links at the bottom of the Oauth screen.

### Relevant log output

```shell

```

### flutter doctor -v

```shell
[!] Flutter (Channel stable, 3.27.3, on Microsoft Windows [Version 10.0.26100.3037], locale en-US)
    • Flutter version 3.27.3 on channel stable at D:\flutter
    ! Warning: `flutter` on your path resolves to D:\projects\...\flutter, which is not inside your current Flutter SDK checkout at D:\flutter. Consider adding D:\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (2 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Microsoft\jdk-17.0.13.11-hotspot\bin\java
    • Java version OpenJDK Runtime Environment Microsoft-10376486 (build 17.0.13+11-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio 2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12508038-b607.1)

[√] VS Code (version 1.96.4)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.26100.3037]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 132.0.6834.160
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 132.0.2957.127

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Info.plist (iOS)

```xml

```

### Podfile (iOS)

```code

```

### AndroidManifest.xml

```xml

```

### MainActivity.java

```java

```

### MainActivity.kt

```kotlin

```

### index.html

```html

```

### Info.plist (macOS)

```xml

```
