### ISSUE TITLE
Upgrade issue from 5.0.11 to 6.0.4 or above

### ISSUE THREAD

**Issue by jodijunan** [darwin-morocho/flutter-facebook-auth#449]
### What version are you using?

flutter_facebook_auth: ^5.0.11

### What OS and version are you using to local deploy your application?

Sequoia 15.3

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
name: myapp
description: myapp

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  parse_server_sdk_flutter: ^8.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  carousel_slider: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  smooth_page_indicator: ^1.0.0+2
  datetime_picker_formfield: ^2.0.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
#  flutter_facebook_auth: ^6.0.4 # this version was upgraded but caused warning on pub get and when run in debug
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.2.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6
  firebase_core_platform_interface: ^5.0.0
  dropdown_button2: ^2.3.9
  share_plus: ^10.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  timelines_plus: ^1.0.6
  easy_debounce: ^2.0.2+1
  animate_do: ^3.3.4
  dotted_border: ^2.0.0+3
  flutter_speed_dial: ^7.0.0

  flutter_local_notifications: ^18.0.1
  firebase_dynamic_links: ^6.0.11
  audioplayers: ^6.1.0
  sticky_grouped_list: ^3.1.0
  #  package_info_plus: ^4.1.0
  flutter_launcher_icons: ^0.14.2
#  telephony: ^0.2.0
  badges: ^3.1.2
  pin_code_fields: ^8.0.1
  #  syncfusion_flutter_xlsio: ^20.1.58-beta
  sign_in_with_apple: ^6.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/newLogoForeground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

When pub get get the following error:

Package flutter_facebook_auth:macos references facebook_auth_desktop:macos as the default plugin, but the package does not exist, or is not a plugin package.
Ask the maintainers of flutter_facebook_auth to either avoid referencing a default implementation via `platforms: macos: default_package: facebook_auth_desktop` or create a plugin named facebook_auth_desktop.

Package flutter_facebook_auth:macos references facebook_auth_desktop:macos as the default plugin, but the package does not exist, or is not a plugin package.
Ask the maintainers of flutter_facebook_auth to either avoid referencing a default implementation via `platforms: macos: default_package: facebook_auth_desktop` or create a plugin named facebook_auth_desktop.

Package flutter_facebook_auth:macos references facebook_auth_desktop:macos as the default plugin, but the package does not exist, or is not a plugin package.
Ask the maintainers of flutter_facebook_auth to either avoid referencing a default implementation via `platforms: macos: default_package: facebook_auth_desktop` or create a plugin named facebook_auth_desktop.

### Expected Behavior

not showing the error

### To Reproduce

run
flutter pub get

### Relevant log output

```shell

```

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.3 24D60 darwin-arm64, locale en-AU)
    • Flutter version 3.27.1 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (2 months ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Android SDK at /Users/jodijunan/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.97.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile) • 32395A4D-9A05-4C9B-B792-3D9F63B5FD05 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.3 24D60 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.3 24D60 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 133.0.6943.142
    ! Error: Browsing on the local area network for iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Info.plist (iOS)

```xml

```

### Podfile (iOS)

```code

```

### AndroidManifest.xml

```xml

```

### MainActivity.java

```java

```

### MainActivity.kt

```kotlin

```

### index.html

```html

```

### Info.plist (macOS)

```xml

```
