### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by zmeggyesi** [darwin-morocho/flutter-facebook-auth#456]
### What version are you using?

flutter_facebook_auth:7.1.1

### What OS and version are you using to local deploy your application?

Android 15

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
name: site_overwatch
description: Dive Site Overwatch

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
#  collection: 1.17.1
  js: 0.7.1

dependencies:
  # Network
  protobuf: 3.1.0
  cached_network_image: 3.4.1
  http: 1.3.0
  connectivity_plus: 6.1.3

  # Geo
  geolocator: 13.0.2
  location: 8.0.0
#    git:
#      url: https://github.com/781flyingdutchman/flutterlocation.git
#      ref: V4
#      path: packages/location
  geocoding: 3.0.0
#  flutter_google_places_sdk: 0.3.2+8
  flutter_google_places_sdk: ^0.3.10

  # Core
  firebase_core: 3.12.0
  firebase_crashlytics: 4.3.3
  firebase_analytics: 11.4.3
  firebase_auth: 5.5.0
  firebase_remote_config: 5.4.1
  firebase_storage: 12.4.3
  shared_preferences: 2.5.2
  in_app_purchase: 3.2.1
  file_picker: 9.0.0
  fixnum: 1.1.1
  google_sign_in: 6.2.2
  sign_in_with_apple: 6.1.4
  device_info_plus: 11.3.0
  android_id: 0.4.0
  flutter_facebook_auth: 7.1.1
  intl: any # pinned in place by flutter_localization
  logging: any
  uuid: 4.5.1
  equatable: 2.0.7
  provider: 6.1.2
  google_mobile_ads: 5.3.1
  flutter:
    sdk: flutter
  stack_trace: any # pinned in place by flutter_test from the SDK
  path: any # Flutter SDK already defines this and pins it in place

  # UI
  flutter_typeahead: 5.2.0
  onboarding: 4.0.2
  google_maps_flutter: 2.10.0
  incrementally_loading_listview: 1.0.0
  font_awesome_flutter: 10.8.0
  package_info_plus: 8.2.1
  url_launcher: 6.3.1
  rate_my_app: 2.3.1
  intl_phone_number_input: any
  intl_phone_field: 3.2.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: 18.0.1
  flutter_app_badger: 1.5.0
  flutter_rating_bar: 4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.8

  in_app_purchase_android: any
  in_app_purchase_storekit: any

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  mockito: any
  # Incompatible with UUID due to a mismatch in the referenced Crypto package versions
#  flutter_driver:
#    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  fake_async: any # pinned in place by the SDK

flutter_icons:
  image_path_android: assets/app-icon.png
  image_path_ios: ../commons/creatives/app-icon/google/app-icon.png # This is skipped anyway
  android: true
  ios: false

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Describe the Bug

The Facebook login activity goes into an infinite loop if the password is filled by the OS password manager subsystem.

### Expected Behavior

User should be able to log in using their Android password management

### To Reproduce

Start a Facebook login flow, then try to use a saved email/password combination to log into the activity that appears

### Relevant log output

```shell

```

### flutter doctor -v

```shell
# flutter doctor -v
[√] Flutter (Channel stable, 3.27.4, on Microsoft Windows [Version 10.0.26100.3775], locale hu-HU)
    • Flutter version 3.27.4 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8a9f9a52e (3 months ago), 2025-01-31 16:07:18 -0500
    • Engine revision 82bd5b7209
    • Dart version 3.6.2
    • DevTools version 2.40.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc2)
    • Android SDK at C:\tools\android
    • Platform android-35, build-tools 35.0.0-rc2
    • ANDROID_HOME = C:\tools\android
    • Java binary at: F:\jetbrains\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34916.146
    • Windows 10 SDK version 10.0.22000.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2024.3)
    • Android Studio at F:\jetbrains\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[√] IntelliJ IDEA Community Edition (version 2025.1)
    • IntelliJ at F:\jetbrains\IntelliJ IDEA Community Edition
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 251.25267.1

[√] VS Code (version 1.99.1)
    • VS Code at C:\Users\zmegg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • Pixel 8 (mobile)    • 37260DLJH000LN • android-arm64  • Android 15 (API 35)
    • Mi A2 Lite (mobile) • 57870a939905   • android-arm64  • Android 10 (API 29)
    • Windows (desktop)   • windows        • windows-x64    • Microsoft Windows [Version 10.0.26100.3775]
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 135.0.7049.96
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 130.0.2849.56

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Info.plist (iOS)

```xml

```

### Podfile (iOS)

```code

```

### AndroidManifest.xml

```xml

```

### MainActivity.java

```java

```

### MainActivity.kt

```kotlin

```

### index.html

```html

```

### Info.plist (macOS)

```xml

```
