### ISSUE TITLE
flutter_facebook_auth dependency break "path_provider" dependency channel.

### ISSUE THREAD

**Issue by redjamhere** [darwin-morocho/flutter-facebook-auth#93]
**Describe the bug**
When i add "flutter_facebook_auth", other plugins get "No implementation" error
**Environment**
**flutter doctor -v:**
```console
  [√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale ru-RU)
      • Flutter version 2.0.5 at C:\src\flutter
      • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
      • Engine revision b09f014e96
      • Dart version 2.12.3
  
  [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
      • Android SDK at C:\Users\User\AppData\Local\Android\sdk
      • Platform android-30, build-tools 30.0.2
      • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
      • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
      • All Android licenses accepted.
  
  [√] Android Studio (version 4.0)
      • Android Studio at C:\Program Files\Android\Android Studio
      • Flutter plugin version 51.0.1
      • Dart plugin version 193.7547
      • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
  
  [√] Connected device (1 available)
      • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
```
**pubspec.yaml:**
```yaml
  name: projectName
  description: A new Flutter project.
  
  publish_to: 'none' 
  
  version: 1.0.0+1
  
  environment:
    sdk: ">=2.7.0 <3.0.0"
  
  dependencies:
    flutter:
      sdk: flutter
    registration_repository:
      path: packages/registration_repository
    database: 
      path: packages/database
    user_repository: 
      path: packages/user_repository
    profile_repository:
      path: packages/profile_repository
    cupertino_icons: ^1.0.2
    flutter_bloc: any
    bloc: any
    meta: any
    equatable: any
    google_maps_flutter: any
    web_socket_channel: any
    # ext_video_player: any
    font_awesome_flutter: any
    flushbar: any
    country_code_picker: any
    flutter_svg: any
    pin_code_fields: any
    image_picker: ^0.7.4
    flutter_emoji: any
    url_launcher: any
    sizer: any
    intl: any
    flutter_staggered_grid_view: any
    firebase_core: ^1.1.0
  
  
  dev_dependencies:
    flutter_test:
      sdk: flutter
  
  flutter:
    uses-material-design: true
    assets:
```
  
**AndroidManifest.xml:**
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="projectName">
  <uses-permission android:name="android.permission.INTERNET"/>
  <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="projectName"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">

        <meta-data android:name="com.google.android.geo.API_KEY"
          android:value="key"/>
        
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data android:name="io.flutter.network-policy"
              android:resource="@xml/network_security_config"/>
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```
**GeneratedPluginRegistrant.java :**

```java
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin());
    flutterEngine.getPlugins().add(new app.meedu.flutter_facebook_auth.FlutterFacebookAuthPlugin());
    flutterEngine.getPlugins().add(new ru.innim.flutter_login_vk.FlutterLoginVkPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlemaps.GoogleMapsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlesignin.GoogleSignInPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
  }
}
```

**To Reproduce:**

_When i add "flutter_facbook_auth":_

```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.2
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.3+1
  flutter_login_vk: ^1.0.0
  http: ^0.13.2
```
_i have problem here:_

```dart
  createDatabase() async {
   Directory documentsDirectory = await getApplicationDocumentsDirectory();

    String path = join(documentsDirectory.path, "test.db");

    var database = await openDatabase(
      path,
      version: 1,
      onCreate: initDB,
      onUpgrade: onUpgrade,
    );
    return database;
  }
```

**Expected behavior:**

```console
I/flutter (11229): AuthenticationBloc MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider) #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:139:24)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #2      DatabaseProvider.createDatabase (package:database/src/database.dart:26:36)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #3      DatabaseProvider.database (package:database/src/database.dart:20:17)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #4      UserDao.getUserToken (package:database/src/dao/user_dao.dart:7:16)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #5      UserRepository.getUserToken (package:user_repository/src/user_repository.dart:23:21)
I/flutter (11229): <asynchronous suspension>
I/flutter (11229): #6      AuthenticationBloc.mapEventToState (package:projectName/src/bloc/auth/auth_bloc.dart:31:32)
I/flutter (11229): <asynchronous suspension>
E/flutter (11229): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider) occurred in Instance of 'AuthenticationBloc'.
E/flutter (11229): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:139:24)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #2      DatabaseProvider.createDatabase (package:database/src/database.dart:26:36)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #3      DatabaseProvider.database (package:database/src/database.dart:20:17)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #4      UserDao.getUserToken (package:database/src/dao/user_dao.dart:7:16)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #5      UserRepository.getUserToken (package:user_repository/src/user_repository.dart:23:21)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229): #6      AuthenticationBloc.mapEventToState (package:projectName/src/bloc/auth/auth_bloc.dart:31:32)
E/flutter (11229): <asynchronous suspension>
E/flutter (11229):
E/flutter (11229): #0      BlocBase.onError.<anonymous closure> (package:bloc/src/bloc.dart:389:7)
E/flutter (11229): #1      BlocBase.onError (package:bloc/src/bloc.dart:390:6)
E/flutter (11229): #2      _rootRunBinary (dart:async/zone.dart:1378:47)
E/flutter (11229): #3      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
E/flutter (11229): #4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
E/flutter (11229): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (11229): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
E/flutter (11229): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (11229): #8      _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:393:20)
E/flutter (11229): #9      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:323:15)
E/flutter (11229): #10     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:392:5)
E/flutter (11229): #11     _BroadcastStreamController._addError (dart:async/broadcast_stream_controller.dart:290:5)
E/flutter (11229): #12     _rootRunBinary (dart:async/zone.dart:1378:47)
E/flutter (11229): #13     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
E/flutter (11229): #14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
E/flutter (11229): #15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (11229): #16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
E/flutter (11229): #17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (11229): #18     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
E/flutter (11229): #19     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
E/flutter (11229): #20     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter (11229): #21     _rootRunBinary (dart:async/zone.dart:1378:47)
E/flutter (11229): #22     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
E/flutter (11229): #23     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
E/flutter (11229): #24     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (11229): #25     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
E/flutter (11229): #26     _DelayedError.perform (dart:async/stream_impl.dart:602:14)
E/flutter (11229): #27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43468837/116790911-90d0a380-aabf-11eb-8175-f4042d59cf4d.png)
